In [1]:
from xclib.data import data_utils
import numpy as np
import time
import pickle

In [2]:
#Change this later. Make the path as command line argument
X_train = data_utils.read_sparse_file('ass3_parta_data/train_x.txt', force_header=True)
train_class = np.genfromtxt('ass3_parta_data/train_y.txt').reshape(-1, 1)

X_valid = data_utils.read_sparse_file('ass3_parta_data/valid_x.txt', force_header=True)
valid_class = np.genfromtxt('ass3_parta_data/valid_y.txt').reshape(-1, 1)

X_test = data_utils.read_sparse_file('ass3_parta_data/test_x.txt', force_header=True)
test_class = np.genfromtxt('ass3_parta_data/test_y.txt').reshape(-1, 1)

/home/ayushi/.local/lib/python3.6/site-packages/xclib-0.96-py3.6-linux-x86_64.egg/xclib/data/data_utils.py:173: UserWarning: Header mis-match from inferred shape!
  warnings.warn("Header mis-match from inferred shape!")


In [3]:
f = open('ass3_parta_data/train_x.txt') 
m,n = f.readlines()[0].rstrip("\n").split(" ")
m,n = int(m),int(n)
f.close()

In [4]:
classes = np.unique(train_class)
pos_class_ind = np.where(train_class == 1)
neg_class_ind = np.where(train_class == 0)

In [5]:
attributes = np.array(range(X_train.A.shape[1]))

### Entropy H(Y) is calculated assuming Y only has two classes - 0 and 1

###### So we use log_2 and use pos and neg_num

In [6]:
def calc_entropyY(train_data, train_class):
    pos_num = train_data[np.where(train_class == 1)[0]].shape[0]
    neg_num = train_data[np.where(train_class == 0)[0]].shape[0]
    
    if (pos_num == 0) or (neg_num == 0):
        entr = 0 #in the limit
    else:
        entr = (pos_num/(pos_num+neg_num))*np.log2((pos_num+neg_num)/pos_num) + (neg_num/(pos_num+neg_num))*np.log2((pos_num+neg_num)/neg_num)
        
    return entr

In [7]:
#Entropy of Raw data
start = time.time()
print(calc_entropyY(X_train.A, train_class))
print("time = ", time.time()-start)

0.997775157550985
time =  0.11198925971984863


#### Reduction in Error is given by H(Y|X) by using value to split at the node
H(Y|X) 

       = H(Y|X=x)P(X=x)  -- find the two splits 

       = H(Y=y|X=x)P(X=x) -- find the entropy of both the splits. 

       = calc_entropy(split1, train_class_split1).P(X=x)
    

In [8]:
def calc_red_error(train_data, split, split_class, train_class):
    #print("In reduction of Error Module")
    #print(train_data.shape[0])
    error = 0
    for i in range(len(split)):
    #    print("Split shape = ", split[i].shape)
        error += (split[i].shape[0]/train_data.shape[0])*calc_entropyY(split[i], split_class[i])
    #print("Reduction in error = ", error)
    return error


In [9]:
def find_best_attr(train_data, train_class):
    #max_mutual_info = 0;   This doesnt work for the cases when mutual info becomes negative. 
    max_mutual_info = float("-inf");
    median = (np.median(train_data, axis=0))        
    #print(median)
    for i in range(len(attributes)):
        split = []
        split_class = []
        split.append(train_data[np.where(train_data[:,i] <= median[i])])
        split.append(train_data[np.where(train_data[:,i] > median[i])])
        split_class.append(train_class[np.where(train_data[:,i] <= median[i])])
        split_class.append(train_class[np.where(train_data[:,i] > median[i])])
        mutual_info = calc_entropyY(train_data, train_class) - calc_red_error(train_data, split, split_class, train_class)
        #print(mutual_info)
        if max_mutual_info < mutual_info:
            max_mutual_info = mutual_info
            best_attr = attributes[i]
            thres = median[i]
    return max_mutual_info, best_attr, thres

In [10]:
start = time.time()
print(find_best_attr(X_train.A, train_class))
print(time.time()-start)

(0.0793751756882577, 217, 0.0)
42.818392276763916


### Every Node  in the tree will have the following contents:

1. Left Subtree
2. Right Subtree
3. Attribute Name on which this node will split
4. Threshold of the attribute for left and right subtree (Median) - int value
5. Entropy
6. Whether this node is leaf or not - True/False
7. A final value of Y=0 or Y=1 in case of leaf

In [11]:
class newNode(object):
    def __init__(self, attr, Th, value):
        self.left = None
        self.right = None
        self.attribute = attr
        self.threshold = Th
        self.value = value
        self.leaf = False
        self.final = None
        self.parent = None
    
    def find_root(self):
        #root = self
        #print("current node = ",self)
        while (self.parent is not None):
            #print(self.parent)
            self = self.parent
            self = self.find_root()
        root = self
        #print("Root found at = ", root)
        return root

    def calc_accuracy(self, tra_data, tra_classes, val_data, val_classes, test_data, test_classes):
        root = self.find_root()
        print("Root found at = ", root)
        #print(root)
#         print("Hello")
        t_acc = 0; v_acc = 0; tes_acc = 0
        for i in range(len(tra_data)):
            pred = predict(root, tra_data[i])
            if (pred == tra_classes[i]):
                t_acc+=1
        for i in range(len(val_data)):
            pred = predict(root, val_data[i])
            if (pred == val_classes[i]):
                v_acc += 1
        for i in range(len(test_data)):
            pred = predict(root, test_data[i])
            if(pred == test_classes[i]):
                tes_acc+=1
        
        return t_acc/len(tra_classes), v_acc/len(val_classes), tes_acc/len(test_classes);

In [12]:
class Tree(object):
    def __init__(self):
        self.tree = None
    def buildTree(self, data, classes, parent):
        self.tree = growTree(data, classes, parent, 0)

In [13]:
def predict(tree, data):
    if tree is None:
        return -1
    if tree.leaf:
        return tree.final
    if tree.left is None and tree.right is None:
        if tree.value[0] > tree.value[1]:
            return 0
        else:
            return 1
    if data[tree.attribute] <= tree.threshold:
        #print(tree.parent)
        return predict(tree.left, data)
    elif data[tree.attribute] > tree.threshold:
        return predict(tree.right, data)


In [20]:
def growTree(train_data, classes, parent, depth, depth_threshold=20):
    global num_nodes, nodes
    global train_acc, val_acc, test_acc
    pos_num = train_data[np.where(classes == 1)[0]].shape[0]
    neg_num = train_data[np.where(classes == 0)[0]].shape[0]
    print("The number of nodes present in the graph = ", num_nodes)
    #print(neg_num, pos_num)

    if (depth == depth_threshold):
        num_nodes+=1
        leaf = newNode(None, None, None)
        leaf.parent = parent
        leaf.leaf = True
        if (pos_num > neg_num):
            leaf.final = 1
        else:
            leaf.final = 0
        return leaf
            
    elif(pos_num == 0 or neg_num == 0):
        num_nodes+=1
        leaf = newNode(None, None, None)
        leaf.leaf = True
        leaf.parent = parent
        
        if(pos_num != 0):
            leaf.final = 1
        elif(neg_num != 0):
            leaf.final = 0
        return leaf
        
    else:
        mutual_info, best_attr, thresh = find_best_attr(train_data, classes)
        print("Best Attribute with Threshold = ", best_attr, thresh)
        num_nodes+=1
        left_split = train_data[np.where(train_data[:,best_attr] <= thresh)]
        right_split = train_data[np.where(train_data[:,best_attr] > thresh)]
        left_split_class = classes[np.where(train_data[:,best_attr] <= thresh)]
        right_split_class = classes[np.where(train_data[:,best_attr] > thresh)]
        
        if (left_split.shape[0] == 0):
            leaf = newNode(None, None, None)
            leaf.parent = parent
            
            leaf.leaf = True
            pos = left_split[np.where(left_split_class == 1)[0]].shape[0]
            neg = left_split[np.where(left_split_class == 0)[0]].shape[0]
            if (pos>neg):
                leaf.final = 1
            else:
                leaf.final = 0
            return leaf
        elif (right_split.shape[0] == 0):
            leaf = newNode(None, None, None)
            leaf.leaf = True
            leaf.parent = parent
            
            pos = right_split[np.where(right_split_class == 1)[0]].shape[0]
            neg = right_split[np.where(right_split_class == 0)[0]].shape[0]
            if (pos>neg):
                leaf.final = 1
            else:
                leaf.final = 0
            return leaf
        else:
            addNode = newNode(best_attr, thresh, [neg_num, pos_num])
            addNode.parent = parent
            #print(parent)
            print("The value of the class examples in this node = ", addNode.value)
            if (num_nodes%50 == 1):
                nodes.append(num_nodes)
                t, v, tes = addNode.calc_accuracy(X_train.A, train_class, X_valid.A, valid_class, X_test.A, test_class)
                train_acc.append(t)
                val_acc.append(v)
                test_acc.append(tes)
            print("Building left tree on =", left_split.shape[0])
            addNode.left = growTree(left_split, left_split_class, addNode, depth+1)
            print("Building right tree in = ", right_split.shape[0])
            addNode.right = growTree(right_split, right_split_class, addNode, depth+1)
            return addNode

In [21]:
start = time.time()
num_nodes = 0
nodes = []
train_acc=[]; val_acc= []; test_acc = []
root = Tree()
#root = growTree(X_train.A, train_class, 0, 8)
root.buildTree(X_train.A, train_class, None)
print("Time Taken to grow tree = ", time.time() - start)

The number of nodes present in the graph =  0
Best Attribute with Threshold =  217 0.0
The value of the class examples in this node =  [30560, 34153]
Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 47691
The number of nodes present in the graph =  1
Best Attribute with Threshold =  252 0.0
The value of the class examples in this node =  [17868, 29823]
Building left tree on = 43010
The number of nodes present in the graph =  2
Best Attribute with Threshold =  57 0.0
The value of the class examples in this node =  [17724, 25286]
Building left tree on = 39800
The number of nodes present in the graph =  3
Best Attribute with Threshold =  401 0.0
The value of the class examples in this node =  [17359, 22441]
Building left tree on = 37755
The number of nodes present in the graph =  4
Best Attribute with Threshold =  61 1.0
The value of the class examples in this node =  [17202, 20553]
Building left tree on = 19479
The number of nodes present in the graph 

Best Attribute with Threshold =  66 0.0
The value of the class examples in this node =  [29, 5]
Building left tree on = 32
The number of nodes present in the graph =  60
Best Attribute with Threshold =  20 0.0
The value of the class examples in this node =  [29, 3]
Building left tree on = 28
The number of nodes present in the graph =  61
Building right tree in =  4
The number of nodes present in the graph =  62
Building right tree in =  2
The number of nodes present in the graph =  63
Building right tree in =  4
The number of nodes present in the graph =  64
Building right tree in =  75
The number of nodes present in the graph =  65
Best Attribute with Threshold =  104 0.0
The value of the class examples in this node =  [67, 8]
Building left tree on = 74
The number of nodes present in the graph =  66
Best Attribute with Threshold =  115 4.0
The value of the class examples in this node =  [67, 7]
Building left tree on = 51
The number of nodes present in the graph =  67
Best Attribute wi

Best Attribute with Threshold =  22 4.0
The value of the class examples in this node =  [12, 10]
Building left tree on = 12
The number of nodes present in the graph =  128
Best Attribute with Threshold =  22 2.0
The value of the class examples in this node =  [9, 3]
Building left tree on = 6
The number of nodes present in the graph =  129
Best Attribute with Threshold =  34 1.0
The value of the class examples in this node =  [3, 3]
Building left tree on = 4
The number of nodes present in the graph =  130
Building right tree in =  2
The number of nodes present in the graph =  131
Building right tree in =  6
The number of nodes present in the graph =  132
Building right tree in =  10
The number of nodes present in the graph =  133
Best Attribute with Threshold =  151 43.0
The value of the class examples in this node =  [3, 7]
Building left tree on = 8
The number of nodes present in the graph =  134
Best Attribute with Threshold =  22 5.0
The value of the class examples in this node =  [1

Best Attribute with Threshold =  376 0.0
The value of the class examples in this node =  [25, 4]
Building left tree on = 28
The number of nodes present in the graph =  204
Best Attribute with Threshold =  203 4.0
The value of the class examples in this node =  [25, 3]
Building left tree on = 18
The number of nodes present in the graph =  205
Building right tree in =  10
The number of nodes present in the graph =  206
Building right tree in =  1
The number of nodes present in the graph =  207
Building right tree in =  2
The number of nodes present in the graph =  208
Building right tree in =  2
The number of nodes present in the graph =  209
Building right tree in =  268
The number of nodes present in the graph =  210
Best Attribute with Threshold =  138 92.0
The value of the class examples in this node =  [74, 194]
Building left tree on = 136
The number of nodes present in the graph =  211
Best Attribute with Threshold =  114 0.0
The value of the class examples in this node =  [65, 71]

Best Attribute with Threshold =  186 0.0
The value of the class examples in this node =  [424, 1199]
Building left tree on = 1464
The number of nodes present in the graph =  292
Best Attribute with Threshold =  90 0.0
The value of the class examples in this node =  [329, 1135]
Building left tree on = 915
The number of nodes present in the graph =  293
Best Attribute with Threshold =  27 0.0
The value of the class examples in this node =  [275, 640]
Building left tree on = 744
The number of nodes present in the graph =  294
Best Attribute with Threshold =  245 5.0
The value of the class examples in this node =  [175, 569]
Building left tree on = 376
The number of nodes present in the graph =  295
Best Attribute with Threshold =  100 1.0
The value of the class examples in this node =  [127, 249]
Building left tree on = 205
The number of nodes present in the graph =  296
Best Attribute with Threshold =  80 0.0
The value of the class examples in this node =  [103, 102]
Building left tree o

Best Attribute with Threshold =  88 0.0
The value of the class examples in this node =  [44, 320]
Building left tree on = 308
The number of nodes present in the graph =  356
Best Attribute with Threshold =  15 0.0
The value of the class examples in this node =  [28, 280]
Building left tree on = 285
The number of nodes present in the graph =  357
Best Attribute with Threshold =  119 0.0
The value of the class examples in this node =  [28, 257]
Building left tree on = 284
The number of nodes present in the graph =  358
Best Attribute with Threshold =  152 0.0
The value of the class examples in this node =  [27, 257]
Building left tree on = 283
The number of nodes present in the graph =  359
Best Attribute with Threshold =  121 3.0
The value of the class examples in this node =  [26, 257]
Building left tree on = 143
The number of nodes present in the graph =  360
Building right tree in =  140
The number of nodes present in the graph =  361
Building right tree in =  1
The number of nodes p

Best Attribute with Threshold =  233 0.0
The value of the class examples in this node =  [4, 351]
Building left tree on = 300
The number of nodes present in the graph =  427
Building right tree in =  55
The number of nodes present in the graph =  428
Best Attribute with Threshold =  118 273.0
The value of the class examples in this node =  [4, 51]
Building left tree on = 47
The number of nodes present in the graph =  429
Best Attribute with Threshold =  49 1.0
The value of the class examples in this node =  [2, 45]
Building left tree on = 35
The number of nodes present in the graph =  430
Best Attribute with Threshold =  34 2.0
The value of the class examples in this node =  [2, 33]
Building left tree on = 26
The number of nodes present in the graph =  431
Best Attribute with Threshold =  141 1.0
The value of the class examples in this node =  [2, 24]
Building left tree on = 22
The number of nodes present in the graph =  432
Best Attribute with Threshold =  71 9.0
The value of the clas

Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 4
The number of nodes present in the graph =  501
Best Attribute with Threshold =  15 0.0
The value of the class examples in this node =  [1, 3]
Building left tree on = 3
The number of nodes present in the graph =  502
Building right tree in =  1
The number of nodes present in the graph =  503
Building right tree in =  4
The number of nodes present in the graph =  504
Building right tree in =  2
The number of nodes present in the graph =  505
Building right tree in =  4
The number of nodes present in the graph =  506
Building right tree in =  159
The number of nodes present in the graph =  507
Best Attribute with Threshold =  121 4.0
The value of the class examples in this node =  [95, 64]
Building left tree on = 88
The number of nodes present in the graph =  508
Best Attribute with Threshold =  101 0.0
The value of the class examples in this node =  [35, 53]
Building left tree on = 75
The number of no

Best Attribute with Threshold =  114 0.0
The value of the class examples in this node =  [2, 439]
Building left tree on = 440
The number of nodes present in the graph =  578
Best Attribute with Threshold =  151 6.0
The value of the class examples in this node =  [1, 439]
Building left tree on = 275
The number of nodes present in the graph =  579
Best Attribute with Threshold =  375 0.0
The value of the class examples in this node =  [1, 274]
Building left tree on = 245
The number of nodes present in the graph =  580
Best Attribute with Threshold =  5 1.0
The value of the class examples in this node =  [1, 244]
Building left tree on = 243
The number of nodes present in the graph =  581
Best Attribute with Threshold =  0 0.0
Building right tree in =  2
The number of nodes present in the graph =  582
Building right tree in =  30
The number of nodes present in the graph =  583
Building right tree in =  165
The number of nodes present in the graph =  584
Building right tree in =  1
The numb

Best Attribute with Threshold =  0 0.0
Building right tree in =  2
The number of nodes present in the graph =  656
Building right tree in =  8
The number of nodes present in the graph =  657
Best Attribute with Threshold =  151 5.5
The value of the class examples in this node =  [2, 6]
Building left tree on = 4
The number of nodes present in the graph =  658
Building right tree in =  4
The number of nodes present in the graph =  659
Best Attribute with Threshold =  151 13.5
The value of the class examples in this node =  [2, 2]
Building left tree on = 2
The number of nodes present in the graph =  660
Building right tree in =  2
The number of nodes present in the graph =  661
Building right tree in =  14
The number of nodes present in the graph =  662
Best Attribute with Threshold =  15 0.0
The value of the class examples in this node =  [1, 13]
Building left tree on = 13
The number of nodes present in the graph =  663
Building right tree in =  1
The number of nodes present in the graph

The number of nodes present in the graph =  726
Building right tree in =  3940
The number of nodes present in the graph =  727
Best Attribute with Threshold =  405 0.0
The value of the class examples in this node =  [743, 3197]
Building left tree on = 2716
The number of nodes present in the graph =  728
Best Attribute with Threshold =  113 0.0
The value of the class examples in this node =  [702, 2014]
Building left tree on = 2446
The number of nodes present in the graph =  729
Best Attribute with Threshold =  186 0.0
The value of the class examples in this node =  [527, 1919]
Building left tree on = 2218
The number of nodes present in the graph =  730
Best Attribute with Threshold =  400 0.0
The value of the class examples in this node =  [408, 1810]
Building left tree on = 2148
The number of nodes present in the graph =  731
Best Attribute with Threshold =  233 0.0
The value of the class examples in this node =  [358, 1790]
Building left tree on = 1312
The number of nodes present in 

Best Attribute with Threshold =  354 10.0
The value of the class examples in this node =  [29, 9]
Building left tree on = 28
The number of nodes present in the graph =  789
Building right tree in =  10
The number of nodes present in the graph =  790
Building right tree in =  1
The number of nodes present in the graph =  791
Building right tree in =  11
The number of nodes present in the graph =  792
Best Attribute with Threshold =  129 0.0
The value of the class examples in this node =  [2, 9]
Building left tree on = 8
The number of nodes present in the graph =  793
Building right tree in =  3
The number of nodes present in the graph =  794
Best Attribute with Threshold =  0 0.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  795
Building right tree in =  1
The number of nodes present in the graph =  796
Building right tree in =  12
The number of nodes present in the graph =  797
Building right tree in =  96
T

Best Attribute with Threshold =  174 0.0
The value of the class examples in this node =  [50, 786]
Building left tree on = 817
The number of nodes present in the graph =  868
Best Attribute with Threshold =  353 2.0
The value of the class examples in this node =  [40, 777]
Building left tree on = 409
The number of nodes present in the graph =  869
Best Attribute with Threshold =  27 0.0
The value of the class examples in this node =  [34, 375]
Building left tree on = 392
The number of nodes present in the graph =  870
Best Attribute with Threshold =  63 0.0
The value of the class examples in this node =  [25, 367]
Building left tree on = 389
The number of nodes present in the graph =  871
Best Attribute with Threshold =  178 3.0
The value of the class examples in this node =  [22, 367]
Building left tree on = 332
The number of nodes present in the graph =  872
Best Attribute with Threshold =  203 52.0
The value of the class examples in this node =  [13, 319]
Building left tree on = 171

Best Attribute with Threshold =  121 3.0
The value of the class examples in this node =  [10, 9]
Building left tree on = 10
The number of nodes present in the graph =  934
Best Attribute with Threshold =  19 3.0
The value of the class examples in this node =  [8, 2]
Building left tree on = 9
The number of nodes present in the graph =  935
Best Attribute with Threshold =  24 91.0
The value of the class examples in this node =  [8, 1]
Building left tree on = 6
The number of nodes present in the graph =  936
Building right tree in =  3
The number of nodes present in the graph =  937
Best Attribute with Threshold =  27 241.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  938
Best Attribute with Threshold =  27 155.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  939
Building right tree in =  1
The number of nodes present in the graph = 

Best Attribute with Threshold =  66 0.0
The value of the class examples in this node =  [19, 5]
Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 22
The number of nodes present in the graph =  1001
Best Attribute with Threshold =  27 0.0
The value of the class examples in this node =  [19, 3]
Building left tree on = 19
The number of nodes present in the graph =  1002
Best Attribute with Threshold =  109 0.0
The value of the class examples in this node =  [18, 1]
Building left tree on = 18
The number of nodes present in the graph =  1003
Building right tree in =  1
The number of nodes present in the graph =  1004
Building right tree in =  3
The number of nodes present in the graph =  1005
Best Attribute with Threshold =  20 1.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  1006
Building right tree in =  1
The number of nodes present in the graph =  1007
Building right tree i

Best Attribute with Threshold =  0 0.0
The value of the class examples in this node =  [4, 7]
Building left tree on = 10
The number of nodes present in the graph =  1068
Best Attribute with Threshold =  93 0.0
The value of the class examples in this node =  [3, 7]
Building left tree on = 6
The number of nodes present in the graph =  1069
Best Attribute with Threshold =  65 0.0
The value of the class examples in this node =  [3, 3]
Building left tree on = 5
The number of nodes present in the graph =  1070
Best Attribute with Threshold =  210 21.0
The value of the class examples in this node =  [2, 3]
Building left tree on = 3
The number of nodes present in the graph =  1071
Best Attribute with Threshold =  19 2.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  1072
Best Attribute with Threshold =  15 3.0
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present

Best Attribute with Threshold =  115 6.0
The value of the class examples in this node =  [16, 4]
Building left tree on = 10
The number of nodes present in the graph =  1139
Building right tree in =  10
The number of nodes present in the graph =  1140
Best Attribute with Threshold =  80 2.0
The value of the class examples in this node =  [6, 4]
Building left tree on = 6
The number of nodes present in the graph =  1141
Best Attribute with Threshold =  90 5.0
The value of the class examples in this node =  [5, 1]
Building left tree on = 4
The number of nodes present in the graph =  1142
Building right tree in =  2
The number of nodes present in the graph =  1143
Best Attribute with Threshold =  20 2840.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  1144
Building right tree in =  1
The number of nodes present in the graph =  1145
Building right tree in =  4
The number of nodes present in the graph =  1146
Best 

Best Attribute with Threshold =  80 56463.0
The value of the class examples in this node =  [1, 654]
Building left tree on = 328
The number of nodes present in the graph =  1207
Building right tree in =  327
The number of nodes present in the graph =  1208
Best Attribute with Threshold =  80 67956.0
The value of the class examples in this node =  [1, 326]
Building left tree on = 164
The number of nodes present in the graph =  1209
Building right tree in =  163
The number of nodes present in the graph =  1210
Best Attribute with Threshold =  80 76027.0
The value of the class examples in this node =  [1, 162]
Building left tree on = 82
The number of nodes present in the graph =  1211
Building right tree in =  81
The number of nodes present in the graph =  1212
Best Attribute with Threshold =  80 85636.0
The value of the class examples in this node =  [1, 80]
Building left tree on = 41
The number of nodes present in the graph =  1213
Best Attribute with Threshold =  80 80414.0
The value o

Best Attribute with Threshold =  80 90992.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  1277
Building right tree in =  1
The number of nodes present in the graph =  1278
Building right tree in =  2
The number of nodes present in the graph =  1279
Building right tree in =  8
The number of nodes present in the graph =  1280
Building right tree in =  171
The number of nodes present in the graph =  1281
Best Attribute with Threshold =  22 2.0
The value of the class examples in this node =  [13, 158]
Building left tree on = 170
The number of nodes present in the graph =  1282
Best Attribute with Threshold =  20 1.0
The value of the class examples in this node =  [12, 158]
Building left tree on = 156
The number of nodes present in the graph =  1283
Best Attribute with Threshold =  80 56852.5
The value of the class examples in this node =  [10, 146]
Building left tree on = 78
The number of nodes present in the gr

Best Attribute with Threshold =  22 9.0
The value of the class examples in this node =  [2, 6]
Building left tree on = 4
The number of nodes present in the graph =  1348
Building right tree in =  4
The number of nodes present in the graph =  1349
Best Attribute with Threshold =  0 0.0
The value of the class examples in this node =  [2, 2]
Building left tree on = 3
The number of nodes present in the graph =  1350
Best Attribute with Threshold =  36 1.0
The value of the class examples in this node =  [1, 2]
Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 2
The number of nodes present in the graph =  1351
Building right tree in =  1
The number of nodes present in the graph =  1352
Building right tree in =  1
The number of nodes present in the graph =  1353
Building right tree in =  6
The number of nodes present in the graph =  1354
Best Attribute with Threshold =  66 0.0
The value of the class examples in this node =  [5, 1]
Building left tree on = 5
T

Best Attribute with Threshold =  0 0.0
Building right tree in =  1
The number of nodes present in the graph =  1415
Building right tree in =  1
The number of nodes present in the graph =  1416
Building right tree in =  65
The number of nodes present in the graph =  1417
Best Attribute with Threshold =  43 4.0
The value of the class examples in this node =  [42, 23]
Building left tree on = 43
The number of nodes present in the graph =  1418
Best Attribute with Threshold =  27 0.0
The value of the class examples in this node =  [34, 9]
Building left tree on = 36
The number of nodes present in the graph =  1419
Best Attribute with Threshold =  23 0.0
The value of the class examples in this node =  [27, 9]
Building left tree on = 35
The number of nodes present in the graph =  1420
Best Attribute with Threshold =  115 2.0
The value of the class examples in this node =  [27, 8]
Building left tree on = 30
The number of nodes present in the graph =  1421
Building right tree in =  5
The number 

Best Attribute with Threshold =  20 0.0
The value of the class examples in this node =  [2, 8]
Building left tree on = 9
The number of nodes present in the graph =  1480
Building right tree in =  1
The number of nodes present in the graph =  1481
Building right tree in =  2
The number of nodes present in the graph =  1482
Building right tree in =  4
The number of nodes present in the graph =  1483
Building right tree in =  3
The number of nodes present in the graph =  1484
Best Attribute with Threshold =  25 2.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  1485
Best Attribute with Threshold =  0 0.0
Building right tree in =  1
The number of nodes present in the graph =  1486
Building right tree in =  11
The number of nodes present in the graph =  1487
Building right tree in =  16
The number of nodes present in the graph =  1488
Building right tree in =  3
The number of nodes present in the graph =  1489
Bui

The number of nodes present in the graph =  1546
Building right tree in =  2
The number of nodes present in the graph =  1547
Best Attribute with Threshold =  0 0.0
Building right tree in =  21
The number of nodes present in the graph =  1548
Building right tree in =  69
The number of nodes present in the graph =  1549
Building right tree in =  570
The number of nodes present in the graph =  1550
Best Attribute with Threshold =  240 2.0
The value of the class examples in this node =  [404, 166]
Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 327
The number of nodes present in the graph =  1551
Best Attribute with Threshold =  203 31.0
The value of the class examples in this node =  [182, 145]
Building left tree on = 164
The number of nodes present in the graph =  1552
Best Attribute with Threshold =  27 0.0
The value of the class examples in this node =  [59, 105]
Building left tree on = 90
The number of nodes present in the graph =  1553
Best Attri

Best Attribute with Threshold =  209 14.0
The value of the class examples in this node =  [66, 21]
Building left tree on = 79
The number of nodes present in the graph =  1619
Best Attribute with Threshold =  129 0.0
The value of the class examples in this node =  [58, 21]
Building left tree on = 74
The number of nodes present in the graph =  1620
Best Attribute with Threshold =  63 0.0
The value of the class examples in this node =  [53, 21]
Building left tree on = 73
The number of nodes present in the graph =  1621
Building right tree in =  1
The number of nodes present in the graph =  1622
Building right tree in =  5
The number of nodes present in the graph =  1623
Building right tree in =  8
The number of nodes present in the graph =  1624
Building right tree in =  4
The number of nodes present in the graph =  1625
Best Attribute with Threshold =  146 12.5
The value of the class examples in this node =  [1, 3]
Building left tree on = 2
The number of nodes present in the graph =  162

Best Attribute with Threshold =  100 1.0
The value of the class examples in this node =  [557, 138]
Building left tree on = 579
The number of nodes present in the graph =  1704
Best Attribute with Threshold =  43 0.0
The value of the class examples in this node =  [483, 96]
Building left tree on = 528
The number of nodes present in the graph =  1705
Best Attribute with Threshold =  393 0.0
The value of the class examples in this node =  [432, 96]
Building left tree on = 493
The number of nodes present in the graph =  1706
Best Attribute with Threshold =  363 0.0
The value of the class examples in this node =  [397, 96]
Building left tree on = 418
The number of nodes present in the graph =  1707
Best Attribute with Threshold =  84 14.0
The value of the class examples in this node =  [347, 71]
Building left tree on = 331
The number of nodes present in the graph =  1708
Best Attribute with Threshold =  164 1.0
The value of the class examples in this node =  [281, 50]
Building left tree on

Best Attribute with Threshold =  52 0.0
The value of the class examples in this node =  [50, 25]
Building left tree on = 64
The number of nodes present in the graph =  1769
Best Attribute with Threshold =  193 1.0
The value of the class examples in this node =  [39, 25]
Building left tree on = 61
The number of nodes present in the graph =  1770
Best Attribute with Threshold =  121 25.0
The value of the class examples in this node =  [39, 22]
Building left tree on = 56
The number of nodes present in the graph =  1771
Best Attribute with Threshold =  173 2.0
The value of the class examples in this node =  [34, 22]
Building left tree on = 54
The number of nodes present in the graph =  1772
Best Attribute with Threshold =  8 0.0
The value of the class examples in this node =  [32, 22]
Building left tree on = 53
The number of nodes present in the graph =  1773
Best Attribute with Threshold =  67 5.0
The value of the class examples in this node =  [32, 21]
Building left tree on = 52
The numb

Best Attribute with Threshold =  108 0.0
The value of the class examples in this node =  [1025, 149]
Building left tree on = 1150
The number of nodes present in the graph =  1832
Best Attribute with Threshold =  457 0.0
The value of the class examples in this node =  [1001, 149]
Building left tree on = 1126
The number of nodes present in the graph =  1833
Best Attribute with Threshold =  6 0.0
The value of the class examples in this node =  [977, 149]
Building left tree on = 1125
The number of nodes present in the graph =  1834
Building right tree in =  1
The number of nodes present in the graph =  1835
Building right tree in =  24
The number of nodes present in the graph =  1836
Building right tree in =  24
The number of nodes present in the graph =  1837
Building right tree in =  2
The number of nodes present in the graph =  1838
Building right tree in =  141
The number of nodes present in the graph =  1839
Best Attribute with Threshold =  67 1.0
The value of the class examples in th

Best Attribute with Threshold =  27 28.0
The value of the class examples in this node =  [27, 8]
Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 19
The number of nodes present in the graph =  1901
Best Attribute with Threshold =  34 3.0
The value of the class examples in this node =  [13, 6]
Building left tree on = 12
The number of nodes present in the graph =  1902
Building right tree in =  7
The number of nodes present in the graph =  1903
Building right tree in =  16
The number of nodes present in the graph =  1904
Best Attribute with Threshold =  225 1.0
The value of the class examples in this node =  [14, 2]
Building left tree on = 9
The number of nodes present in the graph =  1905
Building right tree in =  7
The number of nodes present in the graph =  1906
Building right tree in =  20
The number of nodes present in the graph =  1907
Best Attribute with Threshold =  83 4.0
The value of the class examples in this node =  [9, 11]
Building left tr

The value of the class examples in this node =  [40, 1]
Building left tree on = 39
The number of nodes present in the graph =  1978
Building right tree in =  2
The number of nodes present in the graph =  1979
Best Attribute with Threshold =  27 44.0
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  1980
Building right tree in =  1
The number of nodes present in the graph =  1981
Building right tree in =  371
The number of nodes present in the graph =  1982
Best Attribute with Threshold =  391 0.0
The value of the class examples in this node =  [252, 119]
Building left tree on = 244
The number of nodes present in the graph =  1983
Best Attribute with Threshold =  110 0.0
The value of the class examples in this node =  [193, 51]
Building left tree on = 186
The number of nodes present in the graph =  1984
Best Attribute with Threshold =  8 0.0
The value of the class examples in this node =  [136, 50]
Building left 

Best Attribute with Threshold =  107 328.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  2057
Building right tree in =  1
The number of nodes present in the graph =  2058
Building right tree in =  2
The number of nodes present in the graph =  2059
Building right tree in =  37
The number of nodes present in the graph =  2060
Best Attribute with Threshold =  151 63.0
The value of the class examples in this node =  [29, 8]
Building left tree on = 21
The number of nodes present in the graph =  2061
Best Attribute with Threshold =  182 0.0
The value of the class examples in this node =  [13, 8]
Building left tree on = 17
The number of nodes present in the graph =  2062
Best Attribute with Threshold =  209 20.0
The value of the class examples in this node =  [13, 4]
Building left tree on = 9
The number of nodes present in the graph =  2063
Building right tree in =  8
The number of nodes present in the graph =  206

Best Attribute with Threshold =  0 1.0
Building right tree in =  6
The number of nodes present in the graph =  2132
Building right tree in =  338
The number of nodes present in the graph =  2133
Best Attribute with Threshold =  151 21.0
The value of the class examples in this node =  [48, 290]
Building left tree on = 170
The number of nodes present in the graph =  2134
Best Attribute with Threshold =  67 13.0
The value of the class examples in this node =  [45, 125]
Building left tree on = 127
The number of nodes present in the graph =  2135
Best Attribute with Threshold =  230 5.0
The value of the class examples in this node =  [43, 84]
Building left tree on = 118
The number of nodes present in the graph =  2136
Best Attribute with Threshold =  368 0.0
The value of the class examples in this node =  [43, 75]
Building left tree on = 113
The number of nodes present in the graph =  2137
Best Attribute with Threshold =  240 0.0
The value of the class examples in this node =  [43, 70]
Buil

Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 6
The number of nodes present in the graph =  2201
Building right tree in =  4
The number of nodes present in the graph =  2202
Best Attribute with Threshold =  20 3.5
The value of the class examples in this node =  [2, 2]
Building left tree on = 2
The number of nodes present in the graph =  2203
Building right tree in =  2
The number of nodes present in the graph =  2204
Building right tree in =  4
The number of nodes present in the graph =  2205
Building right tree in =  85
The number of nodes present in the graph =  2206
Best Attribute with Threshold =  192 0.0
The value of the class examples in this node =  [11, 74]
Building left tree on = 80
The number of nodes present in the graph =  2207
Best Attribute with Threshold =  80 1.0
The value of the class examples in this node =  [6, 74]
Building left tree on = 47
The number of nodes present in the graph =  2208
Building right tree in =  33
The number

Best Attribute with Threshold =  198 3.0
The value of the class examples in this node =  [66, 33]
Building left tree on = 77
The number of nodes present in the graph =  2281
Best Attribute with Threshold =  87 1.0
The value of the class examples in this node =  [61, 16]
Building left tree on = 68
The number of nodes present in the graph =  2282
Best Attribute with Threshold =  151 13.0
The value of the class examples in this node =  [58, 10]
Building left tree on = 51
The number of nodes present in the graph =  2283
Best Attribute with Threshold =  0 0.0
Building right tree in =  17
The number of nodes present in the graph =  2284
Building right tree in =  9
The number of nodes present in the graph =  2285
Best Attribute with Threshold =  22 4.0
The value of the class examples in this node =  [3, 6]
Building left tree on = 5
The number of nodes present in the graph =  2286
Building right tree in =  4
The number of nodes present in the graph =  2287
Best Attribute with Threshold =  163 

Best Attribute with Threshold =  206 0.0
The value of the class examples in this node =  [808, 340]
Building left tree on = 1143
The number of nodes present in the graph =  2346
Best Attribute with Threshold =  230 5.0
The value of the class examples in this node =  [807, 336]
Building left tree on = 654
The number of nodes present in the graph =  2347
Best Attribute with Threshold =  183 1.0
The value of the class examples in this node =  [478, 176]
Building left tree on = 623
The number of nodes present in the graph =  2348
Best Attribute with Threshold =  50 0.0
The value of the class examples in this node =  [449, 174]
Building left tree on = 621
The number of nodes present in the graph =  2349
Best Attribute with Threshold =  355 11.0
The value of the class examples in this node =  [447, 174]
Building left tree on = 406
The number of nodes present in the graph =  2350
Best Attribute with Threshold =  22 0.0
The value of the class examples in this node =  [288, 118]
Root found at =

Best Attribute with Threshold =  151 37.0
The value of the class examples in this node =  [33, 14]
Building left tree on = 43
The number of nodes present in the graph =  2410
Building right tree in =  4
The number of nodes present in the graph =  2411
Building right tree in =  1
The number of nodes present in the graph =  2412
Building right tree in =  1
The number of nodes present in the graph =  2413
Building right tree in =  2
The number of nodes present in the graph =  2414
Building right tree in =  5
The number of nodes present in the graph =  2415
Best Attribute with Threshold =  0 1.0
The value of the class examples in this node =  [1, 4]
Building left tree on = 4
The number of nodes present in the graph =  2416
Building right tree in =  1
The number of nodes present in the graph =  2417
Building right tree in =  272
The number of nodes present in the graph =  2418
Best Attribute with Threshold =  100 33.0
The value of the class examples in this node =  [216, 56]
Building left t

Best Attribute with Threshold =  151 15.0
The value of the class examples in this node =  [7, 4]
Building left tree on = 6
The number of nodes present in the graph =  2480
Best Attribute with Threshold =  84 45.0
The value of the class examples in this node =  [5, 1]
Building left tree on = 4
The number of nodes present in the graph =  2481
Building right tree in =  2
The number of nodes present in the graph =  2482
Best Attribute with Threshold =  19 19.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  2483
Building right tree in =  1
The number of nodes present in the graph =  2484
Building right tree in =  5
The number of nodes present in the graph =  2485
Best Attribute with Threshold =  203 57334.0
The value of the class examples in this node =  [2, 3]
Building left tree on = 3
The number of nodes present in the graph =  2486
Best Attribute with Threshold =  22 0.0
The value of the class examples in this 

Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 3
The number of nodes present in the graph =  2551
Best Attribute with Threshold =  20 32.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  2552
Building right tree in =  1
The number of nodes present in the graph =  2553
Building right tree in =  2
The number of nodes present in the graph =  2554
Building right tree in =  1
The number of nodes present in the graph =  2555
Building right tree in =  2
The number of nodes present in the graph =  2556
Building right tree in =  12
The number of nodes present in the graph =  2557
Best Attribute with Threshold =  104 0.0
The value of the class examples in this node =  [8, 4]
Building left tree on = 10
The number of nodes present in the graph =  2558
Best Attribute with Threshold =  115 14.0
The value of the class examples in this node =  [8, 2]
Building left tree on = 6
The number o

Best Attribute with Threshold =  0 0.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  2637
Best Attribute with Threshold =  15 78.0
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  2638
Building right tree in =  1
The number of nodes present in the graph =  2639
Building right tree in =  1
The number of nodes present in the graph =  2640
Building right tree in =  184
The number of nodes present in the graph =  2641
Best Attribute with Threshold =  354 61.0
The value of the class examples in this node =  [101, 83]
Building left tree on = 125
The number of nodes present in the graph =  2642
Best Attribute with Threshold =  23 0.0
The value of the class examples in this node =  [82, 43]
Building left tree on = 122
The number of nodes present in the graph =  2643
Best Attribute with Threshold =  0 0.0
The value of the class examples in th

Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 4
The number of nodes present in the graph =  2701
Building right tree in =  2
The number of nodes present in the graph =  2702
Building right tree in =  1
The number of nodes present in the graph =  2703
Building right tree in =  1
The number of nodes present in the graph =  2704
Building right tree in =  5
The number of nodes present in the graph =  2705
Building right tree in =  19
The number of nodes present in the graph =  2706
Best Attribute with Threshold =  203 39413.0
The value of the class examples in this node =  [17, 2]
Building left tree on = 10
The number of nodes present in the graph =  2707
Best Attribute with Threshold =  84 59.0
The value of the class examples in this node =  [8, 2]
Building left tree on = 7
The number of nodes present in the graph =  2708
Best Attribute with Threshold =  203 35216.0
The value of the class examples in this node =  [5, 2]
Building left tree on = 4
The 

Best Attribute with Threshold =  21 0.0
The value of the class examples in this node =  [559, 1462]
Building left tree on = 1997
The number of nodes present in the graph =  2767
Best Attribute with Threshold =  105 6.0
The value of the class examples in this node =  [540, 1457]
Building left tree on = 1802
The number of nodes present in the graph =  2768
Best Attribute with Threshold =  100 0.0
The value of the class examples in this node =  [457, 1345]
Building left tree on = 1633
The number of nodes present in the graph =  2769
Best Attribute with Threshold =  118 0.0
The value of the class examples in this node =  [445, 1188]
Building left tree on = 1573
The number of nodes present in the graph =  2770
Building right tree in =  60
The number of nodes present in the graph =  2771
Building right tree in =  169
The number of nodes present in the graph =  2772
Best Attribute with Threshold =  86 0.0
The value of the class examples in this node =  [12, 157]
Building left tree on = 167
Th

Best Attribute with Threshold =  232 3.0
The value of the class examples in this node =  [10, 11]
Building left tree on = 12
The number of nodes present in the graph =  2846
Best Attribute with Threshold =  8 0.0
The value of the class examples in this node =  [10, 2]
Building left tree on = 10
The number of nodes present in the graph =  2847
Building right tree in =  2
The number of nodes present in the graph =  2848
Building right tree in =  9
The number of nodes present in the graph =  2849
Building right tree in =  15
The number of nodes present in the graph =  2850
Building right tree in =  142
The number of nodes present in the graph =  2851
Best Attribute with Threshold =  363 0.0
The value of the class examples in this node =  [117, 25]
Building left tree on = 93
The number of nodes present in the graph =  2852
Best Attribute with Threshold =  109 0.0
The value of the class examples in this node =  [90, 3]
Building left tree on = 91
The number of nodes present in the graph =  2

Best Attribute with Threshold =  84 118.5
The value of the class examples in this node =  [15, 301]
Building left tree on = 158
The number of nodes present in the graph =  2923
Best Attribute with Threshold =  203 14170.5
The value of the class examples in this node =  [12, 146]
Building left tree on = 79
The number of nodes present in the graph =  2924
Best Attribute with Threshold =  201 4.0
The value of the class examples in this node =  [3, 76]
Building left tree on = 72
The number of nodes present in the graph =  2925
Best Attribute with Threshold =  24 177.0
The value of the class examples in this node =  [2, 70]
Building left tree on = 47
The number of nodes present in the graph =  2926
Building right tree in =  25
The number of nodes present in the graph =  2927
Best Attribute with Threshold =  36 18.0
The value of the class examples in this node =  [2, 23]
Building left tree on = 13
The number of nodes present in the graph =  2928
Best Attribute with Threshold =  209 81.0
The 

Best Attribute with Threshold =  90 6.0
The value of the class examples in this node =  [513, 236]
Building left tree on = 713
The number of nodes present in the graph =  2993
Best Attribute with Threshold =  357 65.0
The value of the class examples in this node =  [482, 231]
Building left tree on = 478
The number of nodes present in the graph =  2994
Best Attribute with Threshold =  193 5.0
The value of the class examples in this node =  [336, 142]
Building left tree on = 475
The number of nodes present in the graph =  2995
Best Attribute with Threshold =  67 73.0
The value of the class examples in this node =  [333, 142]
Building left tree on = 453
The number of nodes present in the graph =  2996
Best Attribute with Threshold =  8 4.0
The value of the class examples in this node =  [315, 138]
Building left tree on = 452
The number of nodes present in the graph =  2997
Best Attribute with Threshold =  12 2.0
The value of the class examples in this node =  [315, 137]
Building left tree

Best Attribute with Threshold =  151 707.5
The value of the class examples in this node =  [6, 2]
Building left tree on = 4
The number of nodes present in the graph =  3067
Best Attribute with Threshold =  5 29.0
The value of the class examples in this node =  [2, 2]
Building left tree on = 3
The number of nodes present in the graph =  3068
Best Attribute with Threshold =  20 29.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  3069
Building right tree in =  1
The number of nodes present in the graph =  3070
Building right tree in =  1
The number of nodes present in the graph =  3071
Building right tree in =  4
The number of nodes present in the graph =  3072
Building right tree in =  20
The number of nodes present in the graph =  3073
Best Attribute with Threshold =  64 9.0
The value of the class examples in this node =  [15, 5]
Building left tree on = 18
The number of nodes present in the graph =  3074
Best 

Best Attribute with Threshold =  151 545.0
The value of the class examples in this node =  [39, 68]
Building left tree on = 56
The number of nodes present in the graph =  3139
Best Attribute with Threshold =  151 536.0
The value of the class examples in this node =  [24, 32]
Building left tree on = 29
The number of nodes present in the graph =  3140
Best Attribute with Threshold =  209 151.0
The value of the class examples in this node =  [17, 12]
Building left tree on = 20
The number of nodes present in the graph =  3141
Best Attribute with Threshold =  107 300.0
The value of the class examples in this node =  [9, 11]
Building left tree on = 18
The number of nodes present in the graph =  3142
Building right tree in =  2
The number of nodes present in the graph =  3143
Building right tree in =  9
The number of nodes present in the graph =  3144
Best Attribute with Threshold =  151 532.0
The value of the class examples in this node =  [8, 1]
Building left tree on = 5
The number of nodes

Best Attribute with Threshold =  151 574.0
The value of the class examples in this node =  [8, 11]
Building left tree on = 10
The number of nodes present in the graph =  3217
Best Attribute with Threshold =  209 157.0
The value of the class examples in this node =  [5, 5]
Building left tree on = 7
The number of nodes present in the graph =  3218
Best Attribute with Threshold =  83 1646.0
The value of the class examples in this node =  [3, 4]
Building left tree on = 4
The number of nodes present in the graph =  3219
Building right tree in =  3
The number of nodes present in the graph =  3220
Building right tree in =  3
The number of nodes present in the graph =  3221
Best Attribute with Threshold =  24 182.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  3222
Building right tree in =  1
The number of nodes present in the graph =  3223
Building right tree in =  9
The number of nodes present in the graph =  3224

Best Attribute with Threshold =  141 61.0
The value of the class examples in this node =  [149, 75]
Building left tree on = 216
The number of nodes present in the graph =  3292
Best Attribute with Threshold =  61 209.0
The value of the class examples in this node =  [146, 70]
Building left tree on = 207
The number of nodes present in the graph =  3293
Best Attribute with Threshold =  107 300.0
The value of the class examples in this node =  [138, 69]
Building left tree on = 184
The number of nodes present in the graph =  3294
Best Attribute with Threshold =  212 6.0
The value of the class examples in this node =  [120, 64]
Building left tree on = 122
The number of nodes present in the graph =  3295
Best Attribute with Threshold =  209 157.0
The value of the class examples in this node =  [84, 38]
Building left tree on = 64
The number of nodes present in the graph =  3296
Best Attribute with Threshold =  209 152.0
The value of the class examples in this node =  [46, 18]
Building left tr

Best Attribute with Threshold =  208 6.0
The value of the class examples in this node =  [27, 10]
Building left tree on = 35
The number of nodes present in the graph =  3364
Best Attribute with Threshold =  141 61.0
The value of the class examples in this node =  [25, 10]
Building left tree on = 34
The number of nodes present in the graph =  3365
Best Attribute with Threshold =  209 187.0
The value of the class examples in this node =  [24, 10]
Building left tree on = 19
The number of nodes present in the graph =  3366
Building right tree in =  15
The number of nodes present in the graph =  3367
Building right tree in =  1
The number of nodes present in the graph =  3368
Building right tree in =  2
The number of nodes present in the graph =  3369
Building right tree in =  73
The number of nodes present in the graph =  3370
Best Attribute with Threshold =  209 192.0
The value of the class examples in this node =  [49, 24]
Building left tree on = 44
The number of nodes present in the gra

Best Attribute with Threshold =  83 1253.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  3436
Building right tree in =  1
The number of nodes present in the graph =  3437
Building right tree in =  5
The number of nodes present in the graph =  3438
Building right tree in =  9
The number of nodes present in the graph =  3439
Best Attribute with Threshold =  83 1257.0
The value of the class examples in this node =  [6, 3]
Building left tree on = 8
The number of nodes present in the graph =  3440
Best Attribute with Threshold =  80 50.5
The value of the class examples in this node =  [6, 2]
Building left tree on = 4
The number of nodes present in the graph =  3441
Best Attribute with Threshold =  209 114.5
The value of the class examples in this node =  [2, 2]
Building left tree on = 2
The number of nodes present in the graph =  3442
Building right tree in =  2
The number of nodes present in the graph =  3443
Bu

Best Attribute with Threshold =  19 39.0
The value of the class examples in this node =  [2, 11]
Building left tree on = 9
The number of nodes present in the graph =  3513
Best Attribute with Threshold =  20 4.0
The value of the class examples in this node =  [1, 8]
Building left tree on = 6
The number of nodes present in the graph =  3514
Building right tree in =  3
The number of nodes present in the graph =  3515
Best Attribute with Threshold =  24 573.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  3516
Building right tree in =  1
The number of nodes present in the graph =  3517
Building right tree in =  4
The number of nodes present in the graph =  3518
Best Attribute with Threshold =  24 568.5
The value of the class examples in this node =  [1, 3]
Building left tree on = 2
The number of nodes present in the graph =  3519
Building right tree in =  2
The number of nodes present in the graph =  3520
Best A

Best Attribute with Threshold =  80 166.0
The value of the class examples in this node =  [117, 84]
Building left tree on = 121
The number of nodes present in the graph =  3590
Best Attribute with Threshold =  67 73.0
The value of the class examples in this node =  [65, 56]
Building left tree on = 64
The number of nodes present in the graph =  3591
Best Attribute with Threshold =  138 3.5
The value of the class examples in this node =  [30, 34]
Building left tree on = 32
The number of nodes present in the graph =  3592
Building right tree in =  32
The number of nodes present in the graph =  3593
Building right tree in =  57
The number of nodes present in the graph =  3594
Best Attribute with Threshold =  67 81.0
The value of the class examples in this node =  [35, 22]
Building left tree on = 50
The number of nodes present in the graph =  3595
Building right tree in =  7
The number of nodes present in the graph =  3596
Building right tree in =  80
The number of nodes present in the grap

Best Attribute with Threshold =  23 0.0
The value of the class examples in this node =  [16, 85]
Building left tree on = 61
The number of nodes present in the graph =  3664
Best Attribute with Threshold =  8 0.0
The value of the class examples in this node =  [15, 46]
Building left tree on = 58
The number of nodes present in the graph =  3665
Best Attribute with Threshold =  164 0.0
The value of the class examples in this node =  [12, 46]
Building left tree on = 50
The number of nodes present in the graph =  3666
Best Attribute with Threshold =  359 3.0
The value of the class examples in this node =  [7, 43]
Building left tree on = 31
The number of nodes present in the graph =  3667
Best Attribute with Threshold =  27 1.0
The value of the class examples in this node =  [7, 24]
Building left tree on = 30
The number of nodes present in the graph =  3668
Best Attribute with Threshold =  153 0.0
The value of the class examples in this node =  [6, 24]
Building left tree on = 25
The number o

Best Attribute with Threshold =  19 3.0
The value of the class examples in this node =  [7, 205]
Building left tree on = 142
The number of nodes present in the graph =  3731
Best Attribute with Threshold =  151 114.0
The value of the class examples in this node =  [5, 137]
Building left tree on = 90
The number of nodes present in the graph =  3732
Best Attribute with Threshold =  0 0.0
Building right tree in =  52
The number of nodes present in the graph =  3733
Best Attribute with Threshold =  0 0.0
Building right tree in =  70
The number of nodes present in the graph =  3734
Best Attribute with Threshold =  0 0.0
Building right tree in =  2
The number of nodes present in the graph =  3735
Building right tree in =  7
The number of nodes present in the graph =  3736
Building right tree in =  11
The number of nodes present in the graph =  3737
Best Attribute with Threshold =  20 4.0
The value of the class examples in this node =  [1, 10]
Building left tree on = 6
The number of nodes pre

Best Attribute with Threshold =  20 18.0
The value of the class examples in this node =  [3, 4]
Building left tree on = 4
The number of nodes present in the graph =  3811
Best Attribute with Threshold =  154 0.0
The value of the class examples in this node =  [3, 1]
Building left tree on = 3
The number of nodes present in the graph =  3812
Building right tree in =  1
The number of nodes present in the graph =  3813
Building right tree in =  3
The number of nodes present in the graph =  3814
Building right tree in =  246
The number of nodes present in the graph =  3815
Best Attribute with Threshold =  22 2.0
The value of the class examples in this node =  [4, 242]
Building left tree on = 217
The number of nodes present in the graph =  3816
Building right tree in =  29
The number of nodes present in the graph =  3817
Best Attribute with Threshold =  393 0.0
The value of the class examples in this node =  [4, 25]
Building left tree on = 27
The number of nodes present in the graph =  3818


Best Attribute with Threshold =  114 0.0
The value of the class examples in this node =  [77, 58]
Building left tree on = 124
The number of nodes present in the graph =  3878
Best Attribute with Threshold =  22 31.0
The value of the class examples in this node =  [75, 49]
Building left tree on = 117
The number of nodes present in the graph =  3879
Best Attribute with Threshold =  50 22.0
The value of the class examples in this node =  [68, 49]
Building left tree on = 106
The number of nodes present in the graph =  3880
Best Attribute with Threshold =  177 25.0
The value of the class examples in this node =  [65, 41]
Building left tree on = 95
The number of nodes present in the graph =  3881
Best Attribute with Threshold =  109 0.0
The value of the class examples in this node =  [55, 40]
Building left tree on = 93
The number of nodes present in the graph =  3882
Best Attribute with Threshold =  163 0.0
The value of the class examples in this node =  [55, 38]
Building left tree on = 91
T

Best Attribute with Threshold =  34 0.0
The value of the class examples in this node =  [4, 92]
Building left tree on = 54
The number of nodes present in the graph =  3943
Best Attribute with Threshold =  151 32.0
The value of the class examples in this node =  [4, 50]
Building left tree on = 35
The number of nodes present in the graph =  3944
Best Attribute with Threshold =  121 0.0
The value of the class examples in this node =  [4, 31]
Building left tree on = 27
The number of nodes present in the graph =  3945
Best Attribute with Threshold =  230 0.0
The value of the class examples in this node =  [4, 23]
Building left tree on = 24
The number of nodes present in the graph =  3946
Best Attribute with Threshold =  79 0.0
The value of the class examples in this node =  [4, 20]
Building left tree on = 23
The number of nodes present in the graph =  3947
Best Attribute with Threshold =  151 31.0
The value of the class examples in this node =  [4, 19]
Building left tree on = 18
The number 

Best Attribute with Threshold =  119 0.0
The value of the class examples in this node =  [3, 406]
Building left tree on = 408
The number of nodes present in the graph =  4015
Best Attribute with Threshold =  66 0.0
The value of the class examples in this node =  [2, 406]
Building left tree on = 405
The number of nodes present in the graph =  4016
Best Attribute with Threshold =  49 0.0
The value of the class examples in this node =  [1, 404]
Building left tree on = 345
The number of nodes present in the graph =  4017
Building right tree in =  60
The number of nodes present in the graph =  4018
Best Attribute with Threshold =  80 0.0
The value of the class examples in this node =  [1, 59]
Building left tree on = 36
The number of nodes present in the graph =  4019
Building right tree in =  24
The number of nodes present in the graph =  4020
Best Attribute with Threshold =  141 8.0
The value of the class examples in this node =  [1, 23]
Building left tree on = 18
The number of nodes prese

Best Attribute with Threshold =  0 3.0
Building right tree in =  3
The number of nodes present in the graph =  4078
Building right tree in =  43
The number of nodes present in the graph =  4079
Best Attribute with Threshold =  52 0.0
The value of the class examples in this node =  [4, 39]
Building left tree on = 30
The number of nodes present in the graph =  4080
Building right tree in =  13
The number of nodes present in the graph =  4081
Best Attribute with Threshold =  15 0.0
The value of the class examples in this node =  [4, 9]
Building left tree on = 11
The number of nodes present in the graph =  4082
Best Attribute with Threshold =  0 3.0
Building right tree in =  2
The number of nodes present in the graph =  4083
Building right tree in =  2
The number of nodes present in the graph =  4084
Building right tree in =  276
The number of nodes present in the graph =  4085
Best Attribute with Threshold =  213 0.0
The value of the class examples in this node =  [90, 186]
Building left 

Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 17
The number of nodes present in the graph =  4151
Best Attribute with Threshold =  84 8.0
The value of the class examples in this node =  [3, 14]
Building left tree on = 12
The number of nodes present in the graph =  4152
Best Attribute with Threshold =  22 1.0
The value of the class examples in this node =  [3, 9]
Building left tree on = 10
The number of nodes present in the graph =  4153
Best Attribute with Threshold =  151 32.5
The value of the class examples in this node =  [2, 8]
Building left tree on = 5
The number of nodes present in the graph =  4154
Best Attribute with Threshold =  34 0.0
The value of the class examples in this node =  [2, 3]
Building left tree on = 4
The number of nodes present in the graph =  4155
Best Attribute with Threshold =  0 0.0
Building right tree in =  1
The number of nodes present in the graph =  4156
Building right tree in =  5
The number of nodes present in the

Best Attribute with Threshold =  79 2.0
The value of the class examples in this node =  [365, 2845]
Building left tree on = 1657
The number of nodes present in the graph =  4217
Best Attribute with Threshold =  116 0.0
The value of the class examples in this node =  [330, 1327]
Building left tree on = 1478
The number of nodes present in the graph =  4218
Best Attribute with Threshold =  218 0.0
The value of the class examples in this node =  [259, 1219]
Building left tree on = 1417
The number of nodes present in the graph =  4219
Best Attribute with Threshold =  27 0.0
The value of the class examples in this node =  [230, 1187]
Building left tree on = 725
The number of nodes present in the graph =  4220
Best Attribute with Threshold =  108 0.0
The value of the class examples in this node =  [72, 653]
Building left tree on = 716
The number of nodes present in the graph =  4221
Best Attribute with Threshold =  114 0.0
The value of the class examples in this node =  [65, 651]
Building lef

Best Attribute with Threshold =  369 2.0
The value of the class examples in this node =  [18, 140]
Building left tree on = 85
The number of nodes present in the graph =  4286
Best Attribute with Threshold =  160 0.0
The value of the class examples in this node =  [14, 71]
Building left tree on = 80
The number of nodes present in the graph =  4287
Best Attribute with Threshold =  20 0.0
The value of the class examples in this node =  [9, 71]
Building left tree on = 75
The number of nodes present in the graph =  4288
Best Attribute with Threshold =  203 31.0
The value of the class examples in this node =  [5, 70]
Building left tree on = 45
The number of nodes present in the graph =  4289
Best Attribute with Threshold =  154 0.0
The value of the class examples in this node =  [5, 40]
Building left tree on = 26
The number of nodes present in the graph =  4290
Best Attribute with Threshold =  363 3.0
The value of the class examples in this node =  [1, 25]
Building left tree on = 21
The numb

Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 11
The number of nodes present in the graph =  4351
Building right tree in =  3
The number of nodes present in the graph =  4352
Best Attribute with Threshold =  152 0.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  4353
Building right tree in =  1
The number of nodes present in the graph =  4354
Building right tree in =  32
The number of nodes present in the graph =  4355
Best Attribute with Threshold =  245 2.0
The value of the class examples in this node =  [22, 10]
Building left tree on = 26
The number of nodes present in the graph =  4356
Best Attribute with Threshold =  203 12.0
The value of the class examples in this node =  [16, 10]
Building left tree on = 20
The number of nodes present in the graph =  4357
Best Attribute with Threshold =  119 0.0
The value of the class examples in this node =  [15, 5]
Building left 

The number of nodes present in the graph =  4420
Best Attribute with Threshold =  27 1.0
The value of the class examples in this node =  [7, 7]
Building left tree on = 12
The number of nodes present in the graph =  4421
Best Attribute with Threshold =  79 0.0
The value of the class examples in this node =  [7, 5]
Building left tree on = 10
The number of nodes present in the graph =  4422
Best Attribute with Threshold =  80 1.0
The value of the class examples in this node =  [7, 3]
Building left tree on = 7
The number of nodes present in the graph =  4423
Best Attribute with Threshold =  34 1.0
The value of the class examples in this node =  [4, 3]
Building left tree on = 6
The number of nodes present in the graph =  4424
Best Attribute with Threshold =  141 8.5
The value of the class examples in this node =  [4, 2]
Building left tree on = 3
The number of nodes present in the graph =  4425
Building right tree in =  3
The number of nodes present in the graph =  4426
Best Attribute with T

Best Attribute with Threshold =  203 20.0
The value of the class examples in this node =  [2, 15]
Building left tree on = 9
The number of nodes present in the graph =  4499
Building right tree in =  8
The number of nodes present in the graph =  4500
Best Attribute with Threshold =  27 37.0
The value of the class examples in this node =  [2, 6]
Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 4
The number of nodes present in the graph =  4501
Best Attribute with Threshold =  100 10.5
The value of the class examples in this node =  [2, 2]
Building left tree on = 2
The number of nodes present in the graph =  4502
Building right tree in =  2
The number of nodes present in the graph =  4503
Building right tree in =  4
The number of nodes present in the graph =  4504
Building right tree in =  20
The number of nodes present in the graph =  4505
Building right tree in =  12
The number of nodes present in the graph =  4506
Best Attribute with Threshold =  151

Best Attribute with Threshold =  32 0.0
The value of the class examples in this node =  [1, 7]
Building left tree on = 7
The number of nodes present in the graph =  4568
Building right tree in =  1
The number of nodes present in the graph =  4569
Building right tree in =  29
The number of nodes present in the graph =  4570
Best Attribute with Threshold =  129 0.0
The value of the class examples in this node =  [20, 9]
Building left tree on = 15
The number of nodes present in the graph =  4571
Best Attribute with Threshold =  154 1.0
The value of the class examples in this node =  [7, 8]
Building left tree on = 12
The number of nodes present in the graph =  4572
Best Attribute with Threshold =  12 4.0
The value of the class examples in this node =  [4, 8]
Building left tree on = 7
The number of nodes present in the graph =  4573
Best Attribute with Threshold =  83 1.0
The value of the class examples in this node =  [1, 6]
Building left tree on = 5
The number of nodes present in the grap

The number of nodes present in the graph =  4637
Building right tree in =  5
The number of nodes present in the graph =  4638
Best Attribute with Threshold =  49 0.0
The value of the class examples in this node =  [4, 1]
Building left tree on = 4
The number of nodes present in the graph =  4639
Building right tree in =  1
The number of nodes present in the graph =  4640
Building right tree in =  15
The number of nodes present in the graph =  4641
Best Attribute with Threshold =  12 0.0
The value of the class examples in this node =  [1, 14]
Building left tree on = 13
The number of nodes present in the graph =  4642
Building right tree in =  2
The number of nodes present in the graph =  4643
Best Attribute with Threshold =  12 3.0
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  4644
Building right tree in =  1
The number of nodes present in the graph =  4645
Building right tree in =  12
The number of nodes pres

Best Attribute with Threshold =  50 2.0
The value of the class examples in this node =  [1, 9]
Building left tree on = 7
The number of nodes present in the graph =  4706
Building right tree in =  3
The number of nodes present in the graph =  4707
Best Attribute with Threshold =  135 1.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  4708
Building right tree in =  1
The number of nodes present in the graph =  4709
Building right tree in =  6
The number of nodes present in the graph =  4710
Building right tree in =  70
The number of nodes present in the graph =  4711
Building right tree in =  119
The number of nodes present in the graph =  4712
Best Attribute with Threshold =  365 9.0
The value of the class examples in this node =  [26, 93]
Building left tree on = 60
The number of nodes present in the graph =  4713
Best Attribute with Threshold =  181 0.0
The value of the class examples in this node =  [21, 39]

The number of nodes present in the graph =  4771
Best Attribute with Threshold =  391 0.0
The value of the class examples in this node =  [1, 6]
Building left tree on = 5
The number of nodes present in the graph =  4772
Building right tree in =  2
The number of nodes present in the graph =  4773
Best Attribute with Threshold =  5 32.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  4774
Building right tree in =  1
The number of nodes present in the graph =  4775
Building right tree in =  5
The number of nodes present in the graph =  4776
Building right tree in =  18
The number of nodes present in the graph =  4777
Best Attribute with Threshold =  151 62.5
The value of the class examples in this node =  [1, 17]
Building left tree on = 9
The number of nodes present in the graph =  4778
Best Attribute with Threshold =  5 32.0
The value of the class examples in this node =  [1, 8]
Building left tree on = 6
The num

Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 2
The number of nodes present in the graph =  4851
Building right tree in =  2
The number of nodes present in the graph =  4852
Best Attribute with Threshold =  151 63.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  4853
Building right tree in =  1
The number of nodes present in the graph =  4854
Building right tree in =  27
The number of nodes present in the graph =  4855
Best Attribute with Threshold =  34 38.0
The value of the class examples in this node =  [3, 24]
Building left tree on = 16
The number of nodes present in the graph =  4856
Best Attribute with Threshold =  203 64.0
The value of the class examples in this node =  [3, 13]
Building left tree on = 12
The number of nodes present in the graph =  4857
Best Attribute with Threshold =  151 39.5
The value of the class examples in this node =  [1, 11]
Building left t

Best Attribute with Threshold =  203 64.0
The value of the class examples in this node =  [9, 430]
Building left tree on = 384
The number of nodes present in the graph =  4924
Best Attribute with Threshold =  107 40.0
The value of the class examples in this node =  [4, 380]
Building left tree on = 377
The number of nodes present in the graph =  4925
Best Attribute with Threshold =  24 37.0
The value of the class examples in this node =  [3, 374]
Building left tree on = 337
The number of nodes present in the graph =  4926
Best Attribute with Threshold =  209 16.0
The value of the class examples in this node =  [3, 334]
Building left tree on = 259
The number of nodes present in the graph =  4927
Best Attribute with Threshold =  151 82.0
The value of the class examples in this node =  [3, 256]
Building left tree on = 147
The number of nodes present in the graph =  4928
Best Attribute with Threshold =  209 15.0
The value of the class examples in this node =  [2, 145]
Building left tree on 

Best Attribute with Threshold =  0 0.0
Building right tree in =  1
The number of nodes present in the graph =  4990
Building right tree in =  425
The number of nodes present in the graph =  4991
Best Attribute with Threshold =  151 91.0
The value of the class examples in this node =  [3, 422]
Building left tree on = 313
The number of nodes present in the graph =  4992
Best Attribute with Threshold =  203 64.0
The value of the class examples in this node =  [2, 311]
Building left tree on = 312
The number of nodes present in the graph =  4993
Best Attribute with Threshold =  0 0.0
Building right tree in =  1
The number of nodes present in the graph =  4994
Building right tree in =  112
The number of nodes present in the graph =  4995
Best Attribute with Threshold =  151 92.0
The value of the class examples in this node =  [1, 111]
Building left tree on = 76
The number of nodes present in the graph =  4996
Building right tree in =  36
The number of nodes present in the graph =  4997
Best 

Best Attribute with Threshold =  151 553.0
The value of the class examples in this node =  [18, 1346]
Building left tree on = 814
The number of nodes present in the graph =  5067
Best Attribute with Threshold =  209 105.0
The value of the class examples in this node =  [3, 811]
Building left tree on = 410
The number of nodes present in the graph =  5068
Best Attribute with Threshold =  203 60.0
The value of the class examples in this node =  [1, 409]
Building left tree on = 314
The number of nodes present in the graph =  5069
Building right tree in =  96
The number of nodes present in the graph =  5070
Best Attribute with Threshold =  151 520.0
The value of the class examples in this node =  [1, 95]
Building left tree on = 55
The number of nodes present in the graph =  5071
Best Attribute with Threshold =  151 518.0
The value of the class examples in this node =  [1, 54]
Building left tree on = 30
The number of nodes present in the graph =  5072
Best Attribute with Threshold =  151 505

Best Attribute with Threshold =  151 567.0
The value of the class examples in this node =  [4, 68]
Building left tree on = 58
The number of nodes present in the graph =  5140
Best Attribute with Threshold =  209 113.0
The value of the class examples in this node =  [2, 56]
Building left tree on = 33
The number of nodes present in the graph =  5141
Best Attribute with Threshold =  209 111.0
The value of the class examples in this node =  [2, 31]
Building left tree on = 19
The number of nodes present in the graph =  5142
Best Attribute with Threshold =  209 110.0
The value of the class examples in this node =  [1, 18]
Building left tree on = 13
The number of nodes present in the graph =  5143
Best Attribute with Threshold =  209 108.0
The value of the class examples in this node =  [1, 12]
Building left tree on = 7
The number of nodes present in the graph =  5144
Best Attribute with Threshold =  0 0.0
Building right tree in =  6
The number of nodes present in the graph =  5145
Building r

The number of nodes present in the graph =  5214
Building right tree in =  112
The number of nodes present in the graph =  5215
Best Attribute with Threshold =  110 0.0
The value of the class examples in this node =  [30, 82]
Building left tree on = 105
The number of nodes present in the graph =  5216
Best Attribute with Threshold =  132 1.0
The value of the class examples in this node =  [25, 80]
Building left tree on = 93
The number of nodes present in the graph =  5217
Best Attribute with Threshold =  128 0.0
The value of the class examples in this node =  [25, 68]
Building left tree on = 91
The number of nodes present in the graph =  5218
Best Attribute with Threshold =  71 0.0
The value of the class examples in this node =  [23, 68]
Building left tree on = 64
The number of nodes present in the graph =  5219
Best Attribute with Threshold =  87 2.0
The value of the class examples in this node =  [13, 51]
Building left tree on = 62
The number of nodes present in the graph =  5220
Bes

Best Attribute with Threshold =  24 17.0
The value of the class examples in this node =  [11754, 2898]
Building left tree on = 8130
The number of nodes present in the graph =  5277
Best Attribute with Threshold =  109 0.0
The value of the class examples in this node =  [6002, 2128]
Building left tree on = 7612
The number of nodes present in the graph =  5278
Best Attribute with Threshold =  203 107.0
The value of the class examples in this node =  [5776, 1836]
Building left tree on = 3820
The number of nodes present in the graph =  5279
Best Attribute with Threshold =  20 0.0
The value of the class examples in this node =  [3157, 663]
Building left tree on = 2845
The number of nodes present in the graph =  5280
Best Attribute with Threshold =  232 7.0
The value of the class examples in this node =  [2513, 332]
Building left tree on = 2121
The number of nodes present in the graph =  5281
Best Attribute with Threshold =  15 4.0
The value of the class examples in this node =  [1982, 139]


Best Attribute with Threshold =  209 48.0
The value of the class examples in this node =  [31, 4]
Building left tree on = 27
The number of nodes present in the graph =  5340
Best Attribute with Threshold =  209 47.0
The value of the class examples in this node =  [25, 2]
Building left tree on = 16
The number of nodes present in the graph =  5341
Building right tree in =  11
The number of nodes present in the graph =  5342
Best Attribute with Threshold =  151 128.0
The value of the class examples in this node =  [9, 2]
Building left tree on = 6
The number of nodes present in the graph =  5343
Building right tree in =  5
The number of nodes present in the graph =  5344
Building right tree in =  8
The number of nodes present in the graph =  5345
Best Attribute with Threshold =  19 60.5
The value of the class examples in this node =  [6, 2]
Building left tree on = 4
The number of nodes present in the graph =  5346
Best Attribute with Threshold =  209 49.0
The value of the class examples in

Best Attribute with Threshold =  107 23.0
The value of the class examples in this node =  [212, 16]
Building left tree on = 116
The number of nodes present in the graph =  5410
Best Attribute with Threshold =  375 0.0
The value of the class examples in this node =  [103, 13]
Building left tree on = 115
The number of nodes present in the graph =  5411
Best Attribute with Threshold =  8 0.0
The value of the class examples in this node =  [103, 12]
Building left tree on = 100
The number of nodes present in the graph =  5412
Best Attribute with Threshold =  80 42.0
The value of the class examples in this node =  [88, 12]
Building left tree on = 59
The number of nodes present in the graph =  5413
Best Attribute with Threshold =  135 1.0
The value of the class examples in this node =  [55, 4]
Building left tree on = 51
The number of nodes present in the graph =  5414
Best Attribute with Threshold =  225 18.0
The value of the class examples in this node =  [47, 4]
Building left tree on = 27
T

Best Attribute with Threshold =  71 413.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  5480
Building right tree in =  1
The number of nodes present in the graph =  5481
Building right tree in =  3
The number of nodes present in the graph =  5482
Best Attribute with Threshold =  151 61.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  5483
Best Attribute with Threshold =  151 59.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  5484
Building right tree in =  1
The number of nodes present in the graph =  5485
Building right tree in =  1
The number of nodes present in the graph =  5486
Building right tree in =  2
The number of nodes present in the graph =  5487
Building right tree in =  7
The number of nodes present in the graph =  5488
Building right tree in

The number of nodes present in the graph =  5548
Best Attribute with Threshold =  209 49.0
The value of the class examples in this node =  [25, 10]
Building left tree on = 23
The number of nodes present in the graph =  5549
Best Attribute with Threshold =  151 115.0
The value of the class examples in this node =  [15, 8]
Building left tree on = 12
The number of nodes present in the graph =  5550
Building right tree in =  11
The number of nodes present in the graph =  5551
Building right tree in =  12
The number of nodes present in the graph =  5552
Best Attribute with Threshold =  209 50.5
The value of the class examples in this node =  [10, 2]
Building left tree on = 6
The number of nodes present in the graph =  5553
Building right tree in =  6
The number of nodes present in the graph =  5554
Building right tree in =  1
The number of nodes present in the graph =  5555
Building right tree in =  9
The number of nodes present in the graph =  5556
Best Attribute with Threshold =  80 22.0


Best Attribute with Threshold =  151 128.0
The value of the class examples in this node =  [24, 11]
Building left tree on = 23
The number of nodes present in the graph =  5627
Best Attribute with Threshold =  151 125.0
The value of the class examples in this node =  [14, 9]
Building left tree on = 12
The number of nodes present in the graph =  5628
Best Attribute with Threshold =  84 21.0
The value of the class examples in this node =  [9, 3]
Building left tree on = 10
The number of nodes present in the graph =  5629
Best Attribute with Threshold =  178 8.0
The value of the class examples in this node =  [8, 2]
Building left tree on = 6
The number of nodes present in the graph =  5630
Building right tree in =  4
The number of nodes present in the graph =  5631
Building right tree in =  2
The number of nodes present in the graph =  5632
Best Attribute with Threshold =  151 124.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present 

Best Attribute with Threshold =  151 129.0
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  5699
Building right tree in =  1
The number of nodes present in the graph =  5700
Building right tree in =  2
The number of nodes present in the graph =  5701
Building right tree in =  1
The number of nodes present in the graph =  5702
Building right tree in =  78
The number of nodes present in the graph =  5703
Best Attribute with Threshold =  178 8.0
The value of the class examples in this node =  [53, 25]
Building left tree on = 62
The number of nodes present in the graph =  5704
Best Attribute with Threshold =  88 1.0
The value of the class examples in this node =  [40, 22]
Building left tree on = 56
The number of nodes present in the graph =  5705
Best Attribute with Threshold =  19 61.0
The value of the class examples in this node =  [38, 18]
Building left tree on = 46
The number of nodes present in the graph =  57

Best Attribute with Threshold =  71 25.0
The value of the class examples in this node =  [74, 14]
Building left tree on = 75
The number of nodes present in the graph =  5770
Best Attribute with Threshold =  2 0.0
The value of the class examples in this node =  [65, 10]
Building left tree on = 71
The number of nodes present in the graph =  5771
Best Attribute with Threshold =  151 126.0
The value of the class examples in this node =  [61, 10]
Building left tree on = 51
The number of nodes present in the graph =  5772
Best Attribute with Threshold =  209 50.0
The value of the class examples in this node =  [43, 8]
Building left tree on = 42
The number of nodes present in the graph =  5773
Best Attribute with Threshold =  151 125.0
The value of the class examples in this node =  [36, 6]
Building left tree on = 29
The number of nodes present in the graph =  5774
Best Attribute with Threshold =  151 124.0
The value of the class examples in this node =  [25, 4]
Building left tree on = 20
The

Best Attribute with Threshold =  141 90.0
The value of the class examples in this node =  [26, 11]
Building left tree on = 21
The number of nodes present in the graph =  5843
Best Attribute with Threshold =  20 1.0
The value of the class examples in this node =  [18, 3]
Building left tree on = 18
The number of nodes present in the graph =  5844
Building right tree in =  3
The number of nodes present in the graph =  5845
Building right tree in =  16
The number of nodes present in the graph =  5846
Best Attribute with Threshold =  203 38.5
The value of the class examples in this node =  [8, 8]
Building left tree on = 8
The number of nodes present in the graph =  5847
Building right tree in =  8
The number of nodes present in the graph =  5848
Building right tree in =  145
The number of nodes present in the graph =  5849
Best Attribute with Threshold =  83 6.0
The value of the class examples in this node =  [115, 30]
Building left tree on = 83
The number of nodes present in the graph =  5

Best Attribute with Threshold =  0 2.0
Building right tree in =  8
The number of nodes present in the graph =  5915
Best Attribute with Threshold =  201 4.0
The value of the class examples in this node =  [7, 1]
Building left tree on = 6
The number of nodes present in the graph =  5916
Building right tree in =  2
The number of nodes present in the graph =  5917
Best Attribute with Threshold =  0 1.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  5918
Building right tree in =  1
The number of nodes present in the graph =  5919
Building right tree in =  2
The number of nodes present in the graph =  5920
Building right tree in =  9
The number of nodes present in the graph =  5921
Best Attribute with Threshold =  209 131.0
The value of the class examples in this node =  [2, 7]
Building left tree on = 5
The number of nodes present in the graph =  5922
Building right tree in =  4
The number of nodes present in the 

Best Attribute with Threshold =  246 0.0
The value of the class examples in this node =  [19, 1]
Building left tree on = 18
The number of nodes present in the graph =  6000
Building right tree in =  2
The number of nodes present in the graph =  6001
Best Attribute with Threshold =  5 1.0
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  6002
Building right tree in =  1
The number of nodes present in the graph =  6003
Building right tree in =  75
The number of nodes present in the graph =  6004
Best Attribute with Threshold =  182 0.0
The value of the class examples in this node =  [8, 67]
Building left tree on = 67
The number of nodes present in the graph =  6005
Best Attribute with Threshold =  129 1.0
The value of the class examples in this node =  [4, 63]
Building left tree on = 61
The number of nodes present in the graph =  6006
Best Attribute with Threshold =  186 0.0
The value of the class examples in this

Best Attribute with Threshold =  112 0.0
The value of the class examples in this node =  [2513, 1153]
Building left tree on = 3168
The number of nodes present in the graph =  6066
Best Attribute with Threshold =  84 29.0
The value of the class examples in this node =  [2206, 962]
Building left tree on = 2213
The number of nodes present in the graph =  6067
Best Attribute with Threshold =  153 3.0
The value of the class examples in this node =  [1613, 600]
Building left tree on = 2185
The number of nodes present in the graph =  6068
Best Attribute with Threshold =  83 25.0
The value of the class examples in this node =  [1586, 599]
Building left tree on = 1342
The number of nodes present in the graph =  6069
Best Attribute with Threshold =  80 19.0
The value of the class examples in this node =  [1003, 339]
Building left tree on = 687
The number of nodes present in the graph =  6070
Best Attribute with Threshold =  8 0.0
The value of the class examples in this node =  [484, 203]
Buildin

Best Attribute with Threshold =  80 20.0
The value of the class examples in this node =  [11, 8]
Building left tree on = 18
The number of nodes present in the graph =  6137
Building right tree in =  1
The number of nodes present in the graph =  6138
Building right tree in =  8
The number of nodes present in the graph =  6139
Best Attribute with Threshold =  19 73.0
The value of the class examples in this node =  [7, 1]
Building left tree on = 5
The number of nodes present in the graph =  6140
Building right tree in =  3
The number of nodes present in the graph =  6141
Building right tree in =  13
The number of nodes present in the graph =  6142
Building right tree in =  263
The number of nodes present in the graph =  6143
Best Attribute with Threshold =  71 25.0
The value of the class examples in this node =  [202, 61]
Building left tree on = 135
The number of nodes present in the graph =  6144
Best Attribute with Threshold =  87 7.0
The value of the class examples in this node =  [98,

Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 140
The number of nodes present in the graph =  6201
Building right tree in =  112
The number of nodes present in the graph =  6202
Building right tree in =  141
The number of nodes present in the graph =  6203
Best Attribute with Threshold =  178 8.0
The value of the class examples in this node =  [103, 38]
Building left tree on = 87
The number of nodes present in the graph =  6204
Building right tree in =  54
The number of nodes present in the graph =  6205
Building right tree in =  2
The number of nodes present in the graph =  6206
Building right tree in =  376
The number of nodes present in the graph =  6207
Best Attribute with Threshold =  368 0.0
The value of the class examples in this node =  [245, 131]
Building left tree on = 369
The number of nodes present in the graph =  6208
Best Attribute with Threshold =  115 28.0
The value of the class examples in this node =  [243, 126]
Building left tre

Best Attribute with Threshold =  151 106.0
The value of the class examples in this node =  [116, 150]
Building left tree on = 151
The number of nodes present in the graph =  6270
Best Attribute with Threshold =  232 15.0
The value of the class examples in this node =  [53, 98]
Building left tree on = 97
The number of nodes present in the graph =  6271
Best Attribute with Threshold =  178 7.0
The value of the class examples in this node =  [28, 69]
Building left tree on = 81
The number of nodes present in the graph =  6272
Best Attribute with Threshold =  209 48.0
The value of the class examples in this node =  [26, 55]
Building left tree on = 53
The number of nodes present in the graph =  6273
Best Attribute with Threshold =  80 14.0
The value of the class examples in this node =  [14, 39]
Building left tree on = 49
The number of nodes present in the graph =  6274
Best Attribute with Threshold =  87 7.0
The value of the class examples in this node =  [14, 35]
Building left tree on = 48

Best Attribute with Threshold =  209 102.0
The value of the class examples in this node =  [71, 46]
Building left tree on = 83
The number of nodes present in the graph =  6341
Best Attribute with Threshold =  19 172.0
The value of the class examples in this node =  [47, 36]
Building left tree on = 76
The number of nodes present in the graph =  6342
Best Attribute with Threshold =  151 229.0
The value of the class examples in this node =  [42, 34]
Building left tree on = 41
The number of nodes present in the graph =  6343
Best Attribute with Threshold =  151 228.0
The value of the class examples in this node =  [25, 16]
Building left tree on = 30
The number of nodes present in the graph =  6344
Building right tree in =  11
The number of nodes present in the graph =  6345
Building right tree in =  35
The number of nodes present in the graph =  6346
Best Attribute with Threshold =  151 235.0
The value of the class examples in this node =  [17, 18]
Building left tree on = 19
The number of 

The number of nodes present in the graph =  6407
Building right tree in =  3
The number of nodes present in the graph =  6408
Best Attribute with Threshold =  151 145.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  6409
Building right tree in =  1
The number of nodes present in the graph =  6410
Building right tree in =  19
The number of nodes present in the graph =  6411
Best Attribute with Threshold =  209 55.0
The value of the class examples in this node =  [14, 5]
Building left tree on = 17
The number of nodes present in the graph =  6412
Best Attribute with Threshold =  19 60.0
The value of the class examples in this node =  [12, 5]
Building left tree on = 10
The number of nodes present in the graph =  6413
Best Attribute with Threshold =  151 132.5
The value of the class examples in this node =  [8, 2]
Building left tree on = 5
The number of nodes present in the graph =  6414
Building right tree in =  

Best Attribute with Threshold =  88 1.0
The value of the class examples in this node =  [181, 67]
Building left tree on = 238
The number of nodes present in the graph =  6473
Best Attribute with Threshold =  61 15.0
The value of the class examples in this node =  [171, 67]
Building left tree on = 237
The number of nodes present in the graph =  6474
Building right tree in =  1
The number of nodes present in the graph =  6475
Building right tree in =  10
The number of nodes present in the graph =  6476
Building right tree in =  7
The number of nodes present in the graph =  6477
Best Attribute with Threshold =  24 16.0
The value of the class examples in this node =  [3, 4]
Building left tree on = 5
The number of nodes present in the graph =  6478
Best Attribute with Threshold =  209 51.0
The value of the class examples in this node =  [1, 4]
Building left tree on = 3
The number of nodes present in the graph =  6479
Building right tree in =  2
The number of nodes present in the graph =  64

The number of nodes present in the graph =  6542
Best Attribute with Threshold =  245 14.0
The value of the class examples in this node =  [26, 1]
Building left tree on = 20
The number of nodes present in the graph =  6543
Building right tree in =  7
The number of nodes present in the graph =  6544
Best Attribute with Threshold =  27 40.0
The value of the class examples in this node =  [6, 1]
Building left tree on = 4
The number of nodes present in the graph =  6545
Building right tree in =  3
The number of nodes present in the graph =  6546
Best Attribute with Threshold =  27 45.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  6547
Building right tree in =  1
The number of nodes present in the graph =  6548
Building right tree in =  212
The number of nodes present in the graph =  6549
Best Attribute with Threshold =  29 1.0
The value of the class examples in this node =  [107, 105]
Building left tree on = 20

Best Attribute with Threshold =  34 17.0
The value of the class examples in this node =  [226, 292]
Building left tree on = 475
The number of nodes present in the graph =  6628
Best Attribute with Threshold =  391 0.0
The value of the class examples in this node =  [188, 287]
Building left tree on = 423
The number of nodes present in the graph =  6629
Best Attribute with Threshold =  359 8.0
The value of the class examples in this node =  [182, 241]
Building left tree on = 391
The number of nodes present in the graph =  6630
Best Attribute with Threshold =  118 0.0
The value of the class examples in this node =  [154, 237]
Building left tree on = 385
The number of nodes present in the graph =  6631
Best Attribute with Threshold =  240 3.0
The value of the class examples in this node =  [154, 231]
Building left tree on = 380
The number of nodes present in the graph =  6632
Best Attribute with Threshold =  152 0.0
The value of the class examples in this node =  [150, 230]
Building left t

Best Attribute with Threshold =  20 478.5
The value of the class examples in this node =  [64, 82]
Building left tree on = 73
The number of nodes present in the graph =  6700
Best Attribute with Threshold =  15 5.0
The value of the class examples in this node =  [30, 43]
Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 71
The number of nodes present in the graph =  6701
Best Attribute with Threshold =  20 458.0
The value of the class examples in this node =  [29, 42]
Building left tree on = 37
The number of nodes present in the graph =  6702
Best Attribute with Threshold =  20 430.0
The value of the class examples in this node =  [15, 22]
Building left tree on = 19
The number of nodes present in the graph =  6703
Best Attribute with Threshold =  20 395.0
The value of the class examples in this node =  [7, 12]
Building left tree on = 10
The number of nodes present in the graph =  6704
Best Attribute with Threshold =  20 293.5
The value of the class ex

Best Attribute with Threshold =  20 504.5
The value of the class examples in this node =  [2, 2]
Building left tree on = 2
The number of nodes present in the graph =  6763
Building right tree in =  2
The number of nodes present in the graph =  6764
Building right tree in =  17
The number of nodes present in the graph =  6765
Best Attribute with Threshold =  20 515.0
The value of the class examples in this node =  [7, 10]
Building left tree on = 10
The number of nodes present in the graph =  6766
Best Attribute with Threshold =  20 512.0
The value of the class examples in this node =  [7, 3]
Building left tree on = 6
The number of nodes present in the graph =  6767
Best Attribute with Threshold =  20 509.0
The value of the class examples in this node =  [5, 1]
Building left tree on = 3
The number of nodes present in the graph =  6768
Building right tree in =  3
The number of nodes present in the graph =  6769
Building right tree in =  4
The number of nodes present in the graph =  6770
B

Best Attribute with Threshold =  141 9.0
The value of the class examples in this node =  [6, 46]
Building left tree on = 30
The number of nodes present in the graph =  6849
Best Attribute with Threshold =  207 0.0
The value of the class examples in this node =  [1, 29]
Building left tree on = 27
The number of nodes present in the graph =  6850
Building right tree in =  3
The number of nodes present in the graph =  6851
Best Attribute with Threshold =  15 1.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  6852
Building right tree in =  1
The number of nodes present in the graph =  6853
Building right tree in =  22
The number of nodes present in the graph =  6854
Best Attribute with Threshold =  19 6.0
The value of the class examples in this node =  [5, 17]
Building left tree on = 12
The number of nodes present in the graph =  6855
Best Attribute with Threshold =  171 0.0
The value of the class examples in this

The number of nodes present in the graph =  6915
Best Attribute with Threshold =  376 0.0
The value of the class examples in this node =  [22, 1]
Building left tree on = 22
The number of nodes present in the graph =  6916
Building right tree in =  1
The number of nodes present in the graph =  6917
Building right tree in =  1
The number of nodes present in the graph =  6918
Building right tree in =  11
The number of nodes present in the graph =  6919
Best Attribute with Threshold =  141 90.0
The value of the class examples in this node =  [7, 4]
Building left tree on = 7
The number of nodes present in the graph =  6920
Best Attribute with Threshold =  151 57.0
The value of the class examples in this node =  [3, 4]
Building left tree on = 4
The number of nodes present in the graph =  6921
Best Attribute with Threshold =  81 0.0
The value of the class examples in this node =  [3, 1]
Building left tree on = 3
The number of nodes present in the graph =  6922
Building right tree in =  1
The 

The number of nodes present in the graph =  7002
Building right tree in =  842
The number of nodes present in the graph =  7003
Best Attribute with Threshold =  67 13.0
The value of the class examples in this node =  [831, 11]
Building left tree on = 465
The number of nodes present in the graph =  7004
Best Attribute with Threshold =  88 0.0
The value of the class examples in this node =  [454, 11]
Building left tree on = 464
The number of nodes present in the graph =  7005
Best Attribute with Threshold =  151 42.0
The value of the class examples in this node =  [454, 10]
Building left tree on = 382
The number of nodes present in the graph =  7006
Best Attribute with Threshold =  5 0.0
The value of the class examples in this node =  [372, 10]
Building left tree on = 247
The number of nodes present in the graph =  7007
Best Attribute with Threshold =  83 424.0
The value of the class examples in this node =  [242, 5]
Building left tree on = 153
The number of nodes present in the graph = 

Best Attribute with Threshold =  57 0.0
The value of the class examples in this node =  [1737, 18]
Building left tree on = 1742
The number of nodes present in the graph =  7073
Best Attribute with Threshold =  117 0.0
The value of the class examples in this node =  [1732, 10]
Building left tree on = 1740
The number of nodes present in the graph =  7074
Best Attribute with Threshold =  100 1.0
The value of the class examples in this node =  [1732, 8]
Building left tree on = 1105
The number of nodes present in the graph =  7075
Building right tree in =  635
The number of nodes present in the graph =  7076
Best Attribute with Threshold =  353 11.0
The value of the class examples in this node =  [627, 8]
Building left tree on = 336
The number of nodes present in the graph =  7077
Best Attribute with Threshold =  246 0.0
The value of the class examples in this node =  [328, 8]
Building left tree on = 314
The number of nodes present in the graph =  7078
Best Attribute with Threshold =  2 0.0

Best Attribute with Threshold =  5 0.0
The value of the class examples in this node =  [118, 2]
Building left tree on = 118
The number of nodes present in the graph =  7143
Building right tree in =  2
The number of nodes present in the graph =  7144
Building right tree in =  138
The number of nodes present in the graph =  7145
Best Attribute with Threshold =  363 5.0
The value of the class examples in this node =  [137, 1]
Building left tree on = 120
The number of nodes present in the graph =  7146
Building right tree in =  18
The number of nodes present in the graph =  7147
Best Attribute with Threshold =  233 9.0
The value of the class examples in this node =  [17, 1]
Building left tree on = 12
The number of nodes present in the graph =  7148
Building right tree in =  6
The number of nodes present in the graph =  7149
Best Attribute with Threshold =  19 1120.5
The value of the class examples in this node =  [5, 1]
Building left tree on = 3
The number of nodes present in the graph =  

Best Attribute with Threshold =  364 0.0
The value of the class examples in this node =  [48, 42]
Building left tree on = 74
The number of nodes present in the graph =  7226
Best Attribute with Threshold =  366 1.0
The value of the class examples in this node =  [46, 28]
Building left tree on = 45
The number of nodes present in the graph =  7227
Best Attribute with Threshold =  36 2.0
The value of the class examples in this node =  [20, 25]
Building left tree on = 23
The number of nodes present in the graph =  7228
Best Attribute with Threshold =  177 2.0
The value of the class examples in this node =  [5, 18]
Building left tree on = 13
The number of nodes present in the graph =  7229
Building right tree in =  10
The number of nodes present in the graph =  7230
Best Attribute with Threshold =  5 3.0
The value of the class examples in this node =  [5, 5]
Building left tree on = 5
The number of nodes present in the graph =  7231
Best Attribute with Threshold =  80 350.0
The value of the 

Best Attribute with Threshold =  181 1.0
The value of the class examples in this node =  [6, 47]
Building left tree on = 43
The number of nodes present in the graph =  7312
Building right tree in =  10
The number of nodes present in the graph =  7313
Best Attribute with Threshold =  20 0.5
The value of the class examples in this node =  [6, 4]
Building left tree on = 5
The number of nodes present in the graph =  7314
Best Attribute with Threshold =  154 0.0
The value of the class examples in this node =  [1, 4]
Building left tree on = 4
The number of nodes present in the graph =  7315
Building right tree in =  1
The number of nodes present in the graph =  7316
Building right tree in =  5
The number of nodes present in the graph =  7317
Building right tree in =  570
The number of nodes present in the graph =  7318
Best Attribute with Threshold =  67 76.0
The value of the class examples in this node =  [405, 165]
Building left tree on = 551
The number of nodes present in the graph =  731

Best Attribute with Threshold =  20 534.5
The value of the class examples in this node =  [45, 7]
Building left tree on = 26
The number of nodes present in the graph =  7384
Best Attribute with Threshold =  203 412.0
The value of the class examples in this node =  [24, 2]
Building left tree on = 14
The number of nodes present in the graph =  7385
Best Attribute with Threshold =  83 6.0
The value of the class examples in this node =  [12, 2]
Building left tree on = 9
The number of nodes present in the graph =  7386
Building right tree in =  5
The number of nodes present in the graph =  7387
Best Attribute with Threshold =  20 490.0
The value of the class examples in this node =  [3, 2]
Building left tree on = 3
The number of nodes present in the graph =  7388
Best Attribute with Threshold =  5 8.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  7389
Building right tree in =  1
The number of nodes present in the

Building left tree on = 195
The number of nodes present in the graph =  7451
Best Attribute with Threshold =  203 411.0
The value of the class examples in this node =  [151, 44]
Building left tree on = 123
The number of nodes present in the graph =  7452
Best Attribute with Threshold =  64 4.0
The value of the class examples in this node =  [90, 33]
Building left tree on = 121
The number of nodes present in the graph =  7453
Best Attribute with Threshold =  354 359.0
The value of the class examples in this node =  [90, 31]
Building left tree on = 108
The number of nodes present in the graph =  7454
Best Attribute with Threshold =  115 329.0
The value of the class examples in this node =  [78, 30]
Building left tree on = 62
The number of nodes present in the graph =  7455
Best Attribute with Threshold =  90 7.0
The value of the class examples in this node =  [47, 15]
Building left tree on = 59
The number of nodes present in the graph =  7456
Best Attribute with Threshold =  115 314.0
Th

Best Attribute with Threshold =  203 414.0
The value of the class examples in this node =  [19, 3]
Building left tree on = 13
The number of nodes present in the graph =  7516
Best Attribute with Threshold =  20 356.0
The value of the class examples in this node =  [12, 1]
Building left tree on = 7
The number of nodes present in the graph =  7517
Best Attribute with Threshold =  20 234.0
The value of the class examples in this node =  [6, 1]
Building left tree on = 4
The number of nodes present in the graph =  7518
Building right tree in =  3
The number of nodes present in the graph =  7519
Best Attribute with Threshold =  20 328.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  7520
Building right tree in =  1
The number of nodes present in the graph =  7521
Building right tree in =  6
The number of nodes present in the graph =  7522
Building right tree in =  9
The number of nodes present in the graph =  7523


Best Attribute with Threshold =  138 5.0
The value of the class examples in this node =  [4, 6]
Building left tree on = 7
The number of nodes present in the graph =  7585
Best Attribute with Threshold =  34 101.0
The value of the class examples in this node =  [4, 3]
Building left tree on = 4
The number of nodes present in the graph =  7586
Best Attribute with Threshold =  20 496.5
The value of the class examples in this node =  [3, 1]
Building left tree on = 2
The number of nodes present in the graph =  7587
Best Attribute with Threshold =  20 426.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  7588
Building right tree in =  1
The number of nodes present in the graph =  7589
Building right tree in =  2
The number of nodes present in the graph =  7590
Building right tree in =  3
The number of nodes present in the graph =  7591
Best Attribute with Threshold =  209 130.0
The value of the class examples in this

Best Attribute with Threshold =  357 38.0
The value of the class examples in this node =  [1, 3]
Building left tree on = 3
The number of nodes present in the graph =  7658
Building right tree in =  1
The number of nodes present in the graph =  7659
Building right tree in =  36
The number of nodes present in the graph =  7660
Best Attribute with Threshold =  152 27370.0
The value of the class examples in this node =  [13, 23]
Building left tree on = 18
The number of nodes present in the graph =  7661
Best Attribute with Threshold =  152 22075.0
The value of the class examples in this node =  [4, 14]
Building left tree on = 9
The number of nodes present in the graph =  7662
Best Attribute with Threshold =  34 90.0
The value of the class examples in this node =  [4, 5]
Building left tree on = 5
The number of nodes present in the graph =  7663
Best Attribute with Threshold =  20 1129.0
The value of the class examples in this node =  [3, 2]
Building left tree on = 3
The number of nodes pres

The number of nodes present in the graph =  7737
Best Attribute with Threshold =  123 0.0
The value of the class examples in this node =  [12, 6]
Building left tree on = 17
The number of nodes present in the graph =  7738
Best Attribute with Threshold =  20 1567.0
The value of the class examples in this node =  [12, 5]
Building left tree on = 9
The number of nodes present in the graph =  7739
Best Attribute with Threshold =  84 56.0
The value of the class examples in this node =  [7, 2]
Building left tree on = 7
The number of nodes present in the graph =  7740
Best Attribute with Threshold =  20 1458.0
The value of the class examples in this node =  [6, 1]
Building left tree on = 4
The number of nodes present in the graph =  7741
Building right tree in =  3
The number of nodes present in the graph =  7742
Best Attribute with Threshold =  20 1525.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  7743
Best Attri

Best Attribute with Threshold =  20 8046.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  7800
Best Attribute with Threshold =  20 6439.5
The value of the class examples in this node =  [1, 1]
Root found at =  <__main__.newNode object at 0x7f7ec5177a58>
Building left tree on = 1
The number of nodes present in the graph =  7801
Building right tree in =  1
The number of nodes present in the graph =  7802
Building right tree in =  1
The number of nodes present in the graph =  7803
Building right tree in =  1
The number of nodes present in the graph =  7804
Building right tree in =  1
The number of nodes present in the graph =  7805
Building right tree in =  4
The number of nodes present in the graph =  7806
Building right tree in =  5
The number of nodes present in the graph =  7807
Building right tree in =  56
The number of nodes present in the graph =  7808
Best Attribute with Threshold =  61 81.0
The value of

Best Attribute with Threshold =  204 0.0
The value of the class examples in this node =  [9, 1]
Building left tree on = 8
The number of nodes present in the graph =  7868
Building right tree in =  2
The number of nodes present in the graph =  7869
Best Attribute with Threshold =  20 33.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  7870
Building right tree in =  1
The number of nodes present in the graph =  7871
Building right tree in =  10
The number of nodes present in the graph =  7872
Best Attribute with Threshold =  115 22.5
The value of the class examples in this node =  [4, 6]
Building left tree on = 5
The number of nodes present in the graph =  7873
Building right tree in =  5
The number of nodes present in the graph =  7874
Best Attribute with Threshold =  0 0.0
The value of the class examples in this node =  [4, 1]
Building left tree on = 4
The number of nodes present in the graph =  7875
Building

Best Attribute with Threshold =  2 2.0
The value of the class examples in this node =  [1, 5]
Building left tree on = 4
The number of nodes present in the graph =  7948
Building right tree in =  2
The number of nodes present in the graph =  7949
Best Attribute with Threshold =  2 19.0
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  7950
Building right tree in =  1
The number of nodes present in the graph =  7951
Building right tree in =  49
The number of nodes present in the graph =  7952
Best Attribute with Threshold =  363 2.0
The value of the class examples in this node =  [11, 38]
Building left tree on = 26
The number of nodes present in the graph =  7953
Best Attribute with Threshold =  57 1.5
The value of the class examples in this node =  [11, 15]
Building left tree on = 13
The number of nodes present in the graph =  7954
Best Attribute with Threshold =  363 0.0
The value of the class examples in this n

Best Attribute with Threshold =  15 188.0
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  8018
Building right tree in =  1
The number of nodes present in the graph =  8019
Building right tree in =  21
The number of nodes present in the graph =  8020
Best Attribute with Threshold =  88 0.0
The value of the class examples in this node =  [13, 8]
Building left tree on = 14
The number of nodes present in the graph =  8021
Best Attribute with Threshold =  190 1.0
The value of the class examples in this node =  [11, 3]
Building left tree on = 13
The number of nodes present in the graph =  8022
Best Attribute with Threshold =  63 0.0
The value of the class examples in this node =  [11, 2]
Building left tree on = 8
The number of nodes present in the graph =  8023
Building right tree in =  5
The number of nodes present in the graph =  8024
Best Attribute with Threshold =  27 1.0
The value of the class examples in this 

Best Attribute with Threshold =  22 3.0
The value of the class examples in this node =  [2, 3]
Building left tree on = 3
The number of nodes present in the graph =  8093
Best Attribute with Threshold =  27 1.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  8094
Best Attribute with Threshold =  20 3.5
The value of the class examples in this node =  [1, 1]
Building left tree on = 1
The number of nodes present in the graph =  8095
Building right tree in =  1
The number of nodes present in the graph =  8096
Building right tree in =  1
The number of nodes present in the graph =  8097
Building right tree in =  2
The number of nodes present in the graph =  8098
Building right tree in =  1
The number of nodes present in the graph =  8099
Building right tree in =  5
The number of nodes present in the graph =  8100
Building right tree in =  1
The number of nodes present in the graph =  8101
Building right tree in =  24

Best Attribute with Threshold =  25 0.0
The value of the class examples in this node =  [473, 218]
Building left tree on = 623
The number of nodes present in the graph =  8169
Best Attribute with Threshold =  93 1.0
The value of the class examples in this node =  [405, 218]
Building left tree on = 564
The number of nodes present in the graph =  8170
Best Attribute with Threshold =  198 3.0
The value of the class examples in this node =  [390, 174]
Building left tree on = 417
The number of nodes present in the graph =  8171
Best Attribute with Threshold =  123 0.0
The value of the class examples in this node =  [265, 152]
Building left tree on = 313
The number of nodes present in the graph =  8172
Best Attribute with Threshold =  164 17.0
The value of the class examples in this node =  [181, 132]
Building left tree on = 292
The number of nodes present in the graph =  8173
Best Attribute with Threshold =  239 4.0
The value of the class examples in this node =  [178, 114]
Building left tr

Best Attribute with Threshold =  34 144.0
The value of the class examples in this node =  [5, 8]
Building left tree on = 11
The number of nodes present in the graph =  8233
Best Attribute with Threshold =  115 42.0
The value of the class examples in this node =  [3, 8]
Building left tree on = 6
The number of nodes present in the graph =  8234
Building right tree in =  5
The number of nodes present in the graph =  8235
Best Attribute with Threshold =  203 74.0
The value of the class examples in this node =  [3, 2]
Building left tree on = 3
The number of nodes present in the graph =  8236
Building right tree in =  2
The number of nodes present in the graph =  8237
Building right tree in =  2
The number of nodes present in the graph =  8238
Building right tree in =  3
The number of nodes present in the graph =  8239
Building right tree in =  6
The number of nodes present in the graph =  8240
Building right tree in =  17
The number of nodes present in the graph =  8241
Building right tree 

Building left tree on = 3
The number of nodes present in the graph =  8301
Building right tree in =  3
The number of nodes present in the graph =  8302
Building right tree in =  58
The number of nodes present in the graph =  8303
Best Attribute with Threshold =  20 0.0
The value of the class examples in this node =  [47, 11]
Building left tree on = 55
The number of nodes present in the graph =  8304
Best Attribute with Threshold =  64 1.0
The value of the class examples in this node =  [47, 8]
Building left tree on = 38
The number of nodes present in the graph =  8305
Best Attribute with Threshold =  117 0.0
The value of the class examples in this node =  [30, 8]
Building left tree on = 25
The number of nodes present in the graph =  8306
Best Attribute with Threshold =  357 14.0
The value of the class examples in this node =  [17, 8]
Building left tree on = 22
The number of nodes present in the graph =  8307
Best Attribute with Threshold =  15 12.0
The value of the class examples in th

Best Attribute with Threshold =  245 22.0
The value of the class examples in this node =  [10, 5]
Building left tree on = 9
The number of nodes present in the graph =  8377
Best Attribute with Threshold =  115 45.0
The value of the class examples in this node =  [4, 5]
Building left tree on = 6
The number of nodes present in the graph =  8378
Best Attribute with Threshold =  15 12.0
The value of the class examples in this node =  [4, 2]
Building left tree on = 3
The number of nodes present in the graph =  8379
Best Attribute with Threshold =  24 19.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  8380
Building right tree in =  1
The number of nodes present in the graph =  8381
Building right tree in =  3
The number of nodes present in the graph =  8382
Building right tree in =  3
The number of nodes present in the graph =  8383
Building right tree in =  6
The number of nodes present in the graph =  8384
Build

The number of nodes present in the graph =  8455
Best Attribute with Threshold =  209 38.0
The value of the class examples in this node =  [1, 37]
Building left tree on = 26
The number of nodes present in the graph =  8456
Building right tree in =  12
The number of nodes present in the graph =  8457
Best Attribute with Threshold =  187 1120.0
The value of the class examples in this node =  [1, 11]
Building left tree on = 9
The number of nodes present in the graph =  8458
Building right tree in =  3
The number of nodes present in the graph =  8459
Best Attribute with Threshold =  36 2850.0
The value of the class examples in this node =  [1, 2]
Building left tree on = 2
The number of nodes present in the graph =  8460
Building right tree in =  1
The number of nodes present in the graph =  8461
Building right tree in =  27
The number of nodes present in the graph =  8462
Building right tree in =  2
The number of nodes present in the graph =  8463
Building right tree in =  50
The number of

Best Attribute with Threshold =  154 1.0
The value of the class examples in this node =  [4, 11]
Building left tree on = 12
The number of nodes present in the graph =  8522
Best Attribute with Threshold =  19 10.0
The value of the class examples in this node =  [4, 8]
Building left tree on = 9
The number of nodes present in the graph =  8523
Best Attribute with Threshold =  203 358.0
The value of the class examples in this node =  [2, 7]
Building left tree on = 6
The number of nodes present in the graph =  8524
Best Attribute with Threshold =  209 3.0
The value of the class examples in this node =  [2, 4]
Building left tree on = 3
The number of nodes present in the graph =  8525
Building right tree in =  3
The number of nodes present in the graph =  8526
Best Attribute with Threshold =  27 47.0
The value of the class examples in this node =  [2, 1]
Building left tree on = 2
The number of nodes present in the graph =  8527
Best Attribute with Threshold =  27 46.5
The value of the class 

In [22]:
print("The total number of nodes in the built tree = {}".format(num_nodes))

The total number of nodes in the built tree = 8597


In [26]:
train_acc, val_acc, test_acc = root.tree.calc_accuracy(X_train.A, train_class, X_valid.A, valid_class, X_test.A, test_class)
#val_acc = root.tree.calc_accuracy(X_valid.A, valid_class)
#test_acc = root.tree.calc_accuracy(X_test.A, test_class)

Root found at =  <__main__.newNode object at 0x7f7ec5177a58>


Test Accuracy = 71.67%
Train Accuracy = 
Validation Accuracy = 

In [27]:
print("The Training Accuracy on Full-Grown Tree is = {:2.3f}%".format(train_acc*100))
print("The Vaidation Accuracy on Full-Grown Tree is = {:2.3f}%".format(val_acc*100))
print("The Test Accuracy on Full-Grown Tree is = {:2.3f}%".format(test_acc*100))

The Training Accuracy on Full-Grown Tree is = 81.423%
The Vaidation Accuracy on Full-Grown Tree is = 75.056%
The Test Accuracy on Full-Grown Tree is = 75.504%


##### Depth = 3
The Training Accuracy on Full-Grown Tree is = 66.541%

The Vaidation Accuracy on Full-Grown Tree is = 66.345%

The Test Accuracy on Full-Grown Tree is = 66.715%

##### Depth = 5
The Training Accuracy on Full-Grown Tree is = 68.46846846846847%

The Vaidation Accuracy on Full-Grown Tree is = 67.85184498423882%

The Test Accuracy on Full-Grown Tree is = 68.41592879328728%

##### Depth = 8
The Training Accuracy on Full-Grown Tree is = 74.004%

The Vaidation Accuracy on Full-Grown Tree is = 72.872%

The Test Accuracy on Full-Grown Tree is = 73.488%

##### Dept = 15
The Training Accuracy on Full-Grown Tree is = 79.90511952776103%

The Vaidation Accuracy on Full-Grown Tree is = 76.08937511589097%

The Test Accuracy on Full-Grown Tree is = 76.63529739001437%

##### Depth = 18
The Training Accuracy on Full-Grown Tree is = 81.199%

The Vaidation Accuracy on Full-Grown Tree is = 75.672%

The Test Accuracy on Full-Grown Tree is = 76.121%

##### Depth = 20
The Training Accuracy on Full-Grown Tree is = 81.423%

The Vaidation Accuracy on Full-Grown Tree is = 75.056%

The Test Accuracy on Full-Grown Tree is = 75.504%

##### Depth = 30
The Training Accuracy on Full-Grown Tree is = 83.243%

The Vaidation Accuracy on Full-Grown Tree is = 72.270%

The Test Accuracy on Full-Grown Tree is = 72.050%

In [5]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, train_class)

In [6]:
tree.plot_tree(clf) 

[Text(319.05051113061876, 366.52, 'X[217] <= 1.5\ngini = 0.498\nsamples = 64713\nvalue = [30560, 34153]'),
 Text(257.36407037011065, 360.35999999999996, 'X[363] <= 31.5\ngini = 0.468\nsamples = 47727\nvalue = [17872, 29855]'),
 Text(225.01246732417226, 354.2, 'X[57] <= 0.5\ngini = 0.489\nsamples = 41489\nvalue = [17697, 23792]'),
 Text(174.68336964363738, 348.03999999999996, 'X[401] <= 0.5\ngini = 0.496\nsamples = 38291\nvalue = [17335, 20956]'),
 Text(88.80787074189956, 341.88, 'X[151] <= 8.5\ngini = 0.499\nsamples = 36235\nvalue = [17178, 19057]'),
 Text(34.19124282323241, 335.71999999999997, 'X[107] <= 13.5\ngini = 0.474\nsamples = 14650\nvalue = [5639, 9011]'),
 Text(21.498475631824196, 329.55999999999995, 'X[106] <= 0.5\ngini = 0.493\nsamples = 10045\nvalue = [4437, 5608]'),
 Text(19.75143691552121, 323.4, 'X[21] <= 0.5\ngini = 0.491\nsamples = 9804\nvalue = [4240, 5564]'),
 Text(17.7520326703668, 317.23999999999995, 'X[353] <= 0.5\ngini = 0.489\nsamples = 9692\nvalue = [4130, 556